### ISSUE TITLE
Using rac_signalForSelector, then KVO, causes object to not "respond to" signal'd selector

### ISSUE THREAD

**Issue by mattjgalloway** [ReactiveCocoa/ReactiveCocoa#1280]
I have a failing test showing a problem I'm experiencing - https://github.com/mattjgalloway/ReactiveCocoa/compare/kvo_bug

Basically, if you use `rac_signalForSelector` to add a selector to an instance, and then KVO that object, then `repsondsToSelector` returns `NO` for the selector you implemented.

I mean something like this:

```
[object rac_signalForSelector:selector];
[object respondsToSelector:selector]; // == YES
[[RACObserve(object, value) publish] connect];
[object respondsToSelector:selector]; // == NO
```

Hopefully that makes sense - if not then hopefully the failing test does!

**Comment by jspahrsummers** [comment]
@fpillet Which methods are you trying to intercept?

**Comment by fpillet** [comment]
@jspahrsummers My AppDelegate is a CLLocationManagerDelegate. It implements nearly all the methods, and I also plug into them with `-rac_signalForSelector:fromProtocol:`. I have been trying to round down a case where the swizzling doesn't work. I think I nearly nailed a situation where moving a RACObserve of my AppDelegate to before creating the swizzling signals renders them unusable.

Unfortunately, trying to reproduce this in a simple sample app didn't work. I keep digging (the fact that I can't always repro the problem here but a remote client can on his iPhone slows me down too).
