### ISSUE TITLE
SubscribeNext Not Triggered on Swift

### ISSUE THREAD

**Issue by wajatimur** [ReactiveCocoa/ReactiveCocoa#1630]
Calling `sendNext` will not trigger `subscribeNext` with `.filter` when Swift Compiler - Optimization Level is set to `Fastest [-O]`. Does anyone have workaround on this issue?

**Comment by Rupert-RR** [comment]
We've come across a very similar issue - a method subscribes to a signal which is a long signal chain involving mapping and filtering. When running without any compiler optimisation, everything works as expected. However, when using compiler optimisation it looks as if the closure given for the final mapping is not being retained - the closure itself is never executed but the next event is definitely passing down the chain to the final subscriber (with a nil object). We have only run into this problem using ReactiveCocoa, but obviously that does not mean that it is a ReactiveCocoa bug.
As suggested in one of the above links, we have passed the calling object into the closure's capture group and this seems to solve the problem. I don't like this solution however because it is not really clear why it works - we are basically passing `self` into the capture list as a weak capture, then assigning it strongly inside the closure, even though it is never actually used by the closure.
Will post here if we get any further in tracking this down.
