### ISSUE TITLE
ReactiveCocoa 2.4.4 RACQueueScheduler compile error: "Property with 'retain (or strong)' attribute ... blah"

### ISSUE THREAD

**Issue by fatuhoku** [ReactiveCocoa/ReactiveCocoa#1679]
![screen shot 2015-01-16 at 13 58 00](https://cloud.githubusercontent.com/assets/430233/5777211/0fcd5c9c-9d88-11e4-8150-805eba4788e5.png)

**Comment by fatuhoku** [comment]
Could be related to #1678 but it's not clear whether the backport solves a compile error rather than something else.

**Comment by jspahrsummers** [comment]
This is probably an issue with your CocoaPods setup.

/cc @tonyarnold @ashfurrow

**Comment by fatuhoku** [comment]
Likely...! I haven't seen it since.

**Comment by fatuhoku** [comment]
I have reproduced it again. `Podfile` is nothing much more than:

```ruby
pod 'ReactiveCocoa'
```

When I downgraded to `2.3.x`...

```ruby
pod 'ReactiveCocoa', '~> 2.3.0'
```

The compile problem disappeared.

**Comment by ashfurrow** [comment]
Can you verifying from the changes in the Podfile.lock file which exact versions you were using? I'll compare the two versions of the podspec and see what's up. (A sample project demonstrating the problem might help, too.) 

As long as it's OK with @jspahrsummers , I'd like to continue discussion on this issue, even if it's closed (as it isn't related to ReactiveCocoa directly). That way if someone does have this problem, they'll read about it here instead of opening a new issue.

**Comment by tonyarnold** [comment]
Yeah, sounds to me like the iOS version in the podspec is set too low. I thought I'd raised it recently, but maybe it needs to be higher again?

**Comment by ReDetection** [comment]
Aargh! I've reproduced this issue in a very strange way. 
In a project I'm using ReactiveCocoa and RestKit, so I found very useful to use [SMReactiveRestKit](https://github.com/stefanomondino/SMReactiveRestKit) of @stefanomondino. As I can see now, @fatuhoku also reproduced this issue when used ReactiveViewModel and STMReactive..([ViewController](https://github.com/stefanomondino/STMReactiveViewController)/[Reachability](https://github.com/stefanomondino/STMReactiveReachability) of @stefanomondino). 
I'm using CocoaPods version 0.36.3. I have iOS platform set to 6.0 in the Podfile. 
@ashfurrow have you any idea how to debug this? It seems like pod is building for ios 5.0, but I've checked, every pod has 6.0 as deployment target.
Issue is reproducible on the empty project with this Podfile:
```
platform :ios, '6.0'

pod 'ReactiveCocoa', '~> 2.5'
pod 'RestKit', '~> 0.24.1'
pod 'SMReactiveRestKit', '~> 0.3.0'
```

**Comment by stefanomondino** [comment]
I've been experiencing same problems with my very own libraries (glad you're using them, btw :) ), I'm not setting any version number to ReactiveCocoa dependencies and this surely is my bad as it's not a good practice. However, I've noticed some time ago that the dependency somehow switched from ReactiveCocoa master branch to a 3.0-alpha one (under @ashfurrow 's github, not from the official one).Not sure if this issue is still present, I've been locking ReactiveCocoa to 2.3.x since then in all my projects to solve this

**Comment by ReDetection** [comment]
@stefanomondino I did that too as a workaround but wanted to know if someone has already fixed this. I neither see issue in your library (you're supporting iOS5+) nor is ReactiveCocoa (it supports iOS5+ as well) so everything should work fine, but it does not. So i think it's a bug in cocoapods or Xcode.

**Comment by ReDetection** [comment]
this relates to https://github.com/CocoaPods/CocoaPods/issues/1001.
I found this very interesting https://github.com/armadsen/ORSSerialPort/issues/22. Seems like a workaround from CocoaPods team

**Comment by ReDetection** [comment]
Seems like it's an issue in both ReactiveCocoa and CocoaPods.
In the ReactiveCocoa: presence of `OS_OBJECT_HAVE_OBJC_SUPPORT` does not mean this feature will be enabled, so proper way is to check `OS_OBJECT_USE_OBJC`. 
In the CocoaPods: when deployment target in Podfile is set to iOS 6.0+ or OS X 10.8+, I see no need to opt-out ARC for GCD so `OS_OBJECT_USE_OBJC=0` should not be passed to compiler.
