### ISSUE TITLE
Swift signal disposable model can lead to leaks

### ISSUE THREAD

**Issue by andymatuschak** [ReactiveCocoa/ReactiveCocoa#1701]
I think we still haven't quite gotten the `Disposable` model quite right. Consider:

```swift
let disposable = producer.startWithSignal { signal, disposable in
  disposable.add(signal |> map { $0 } |> observe(next: { println($0) }))
}
disposable.dispose()
```

The `map` `Signal` is leaked.

Perhaps disposal should flow downstream? Not sure.

**Comment by jspahrsummers** [comment]
Thanks for catching this! I've been thinking about this since you pointed it out.

The primary question we need to answer is: _why_ is disposal important for `Signal`s, when they're meant to be producer controlled? In other words, why can't disposal be a concern that's external to the class entirely?

My conclusion: it's important because **`Signal` disposal breaks the retain cycle between a signal and its observers**. This is why infinite signals require explicitly disposal, while finite signals generally do not (because terminating events will result in the same behavior).

As mentioned in chat, I did—in the previous iteration of the Swift APIs—try to make `HotSignal` (the precursor to `Signal`) obey “normal” memory management semantics, but this is way harder to use, because it forces a choice between two obnoxious designs:

 1. `observe` keeps a strong reference to the `Signal`, in which case _all_ observations must be explicitly disposed to avoid leaks.
 1. `observe` keeps a weak reference to the `Signal`, in which case you need to guarantee that a strong reference exists to the `Signal` in some other way.

So, if we agree that we want more convenient memory management than that, we effectively have to create our own retain cycles that can be broken through disposal.

**The primary use case for explicit disposal is cancellation**—for example, a consumer decides to cancel `SignalProducer.startWithSignal` and the associated work. In that scenario, it makes sense that everything attached to the produced `Signal` should get thrown away. It would also be inappropriate to send a completed or error event, because then the act of cancellation itself can result in work by downstream consumers.

Since `Signal` is meant to be producer-controlled, it seems reasonable that the producer should be the one to cancel it. To that end, **I think we should do the following**:

 1. [Return a `Disposable` from `Signal.pipe`](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1700). Disposing it will tear down the signal and its dependents.
 1. Pass a `Disposable` (perhaps a `CompositeDisposable`) into `Signal.init`. Disposing it will tear down the signal and its dependents.
 1. Expose an `addDisposable` method on `Signal` **or** add some kind of disposal handler to `observe`—for consumers to watch for disposal.
 1. Refactor `Signal` operators so that they dispose of created signals when any observees have been disposed.

I'm more certain on the first two points than the latter two, and I'd be open to other ideas too.

**Comment by andymatuschak** [comment]
Thanks for writing all that up. My initial reaction is to agree that items 1, 2, and 4 are necessary. Less sure about 3.
