### ISSUE TITLE
Using model <=> view terminal channels on reusable UITableViewCell grows memory usage

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#1788]
All,

I have a cell that has a label and a `UISwitch`. I bind the `UISwitch` of each displayable cell to `NSUserDefaults` channel of certain key. Here's my code with comments

```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    // dequeu a cell
    MyKindOfCell *cell = [tableView dequeueReusableCellWithIdentifier:MyKindOfCellIdentifier];

    /*
     * check for disposable and tear down any subscriptions
     */
    if (cell.compoundDisposable) {
        [cell.compoundDisposable  dispose];
        cell.compoundDisposable = nil;
    }

    /* 
     * setup the cell for the model
     */
    MyModel *modelObj = self.modelObjects[indexPath.row];
    cell.textLabel.text = modelObj.name;
    cell.modelObjId = modelObj.id;

    NSString *key = [NSString stringWithFormat:@"MyModel-%@", modelObj.id];
    RACChannelTerminal *userDefaultsTerminal = [[NSUserDefaults standardUserDefaults] rac_channelTerminalForKey:key];

    /*
     * Do the two-way binding dance
     */
    RACDisposable *switchDisposable = [cell.theSwitch.rac_newOnChannel subscribe:userDefaultsTerminal];
    RACDisposable *defaultsDisposable = [userDefaultsTerminal subscribe:cell.theSwitch.rac_newOnChannel];

    /*
     * Give the cell disposable object 
     * so that upon reuse we can use it
     */
    cell.compoundDisposable = [RACCompoundDisposable compoundDisposableWithDisposables:@[switchDisposable, defaultsDisposable]];

    return cell;
}
```

I wanted to make sure that the cell does not accumulate the subscriptions I profiled it. Eventhough the code works (i.e. the cell does not rack-up the subscriptions when repeatedly scrolling up & down), I noticed the insane amount of RACCompoundDisposable instances being created (presumably for each cell reuse). This, in turn, makes the memory usage grow for the app. 

I think I am missing `takeUntil:cell.rac_prepareForReuseSignal`. But where should I hook it up in this case?

**Comment by jspahrsummers** [comment]
I haven't tried to trace your disposable lifetimes myself, but is there a reason you can't set your model object on the `cell` directly?

Then, your cell can set up whatever bindings it wants _just one time_, as part of initialization.

**Comment by eimantas** [comment]
But then the problem comes when the cell gets reused for a channel with different key. And the more it gets reused the more subscriptions it will create.

**Comment by jspahrsummers** [comment]
We usually try to structure our table view cells so that they can observe key paths _on themselves_. If you observe through those key paths, you shouldn't need to tear down and recreate observations upon cell reuse.

I have [an example](https://github.com/jspahrsummers/GroceryList/blob/17b83a1563cae1ce0bf3d2f2d8340b58de2ecdf6/GroceryList/GCYGroceryStoreCell.m#L20-L28) of this in my [GroceryList](https://github.com/jspahrsummers/GroceryList) demo app (though note that it's using an obsolete/never-released version of RAC).

This particular case seems like it would really benefit from a view model too. You can create a view model which binds to the model object, and to `NSUserDefaults`, and then just make sure to replace the cell's view model in `-cellForRowAtIndexPath:`.

If you really want to continue with the pattern you have here, you probably need to _observe_ `cell.rac_prepareForReuseSignal`, and manually `sendCompleted` upon the channel terminals at that point.

**Comment by eimantas** [comment]
Thanks for this code sample. Now I just need to figure out how to bind view model with user defaults channel.
