### ISSUE TITLE
Using transducers in conjunction with RAC

### ISSUE THREAD

**Issue by mhallendal** [ReactiveCocoa/ReactiveCocoa#1789]
I'm in the process of releasing a transducer based transformation framework called _MogKit_ for Objective-C (Swift to come) and one of the ideas I had was to use it in combination with Reactive Cocoa in order to create composable transformations and apply them to any `RACStream` (or any other series of values).

Would love to hear some feedback on what you think about this usecase and my implementation as a category on `RACStream` in the _Non-collection use cases_ example in:

https://github.com/mhallendal/MogKit/blob/master/README.md

**Comment by jspahrsummers** [comment]
Very cool! Transducers are awesome. :zap:

It might be worth noting, though, that `RACSignal`s already offer the benefit of transducers—because values are delivered incrementally, and not available all at once (compared to most data structures), all operators perform their work incrementally and don't build up huge intermediate data structures.

For example, mapping then filtering an array is a great use case for transducers, because it allows you to eliminate the intermediate array generated during the mapping. However, for a mapped-then-filtered signal, you never build up that intermediate structure to begin with—values are just mapped and filtered as they percolate from the signal to the final subscribers. :sparkles:

None of that diminishes how cool this is, though! @robrix, in particular, might be interested in this approach too. :smile:

**Comment by mhallendal** [comment]
Thanks a lot for the feedback, really appreciate it.

Agree, the main benefits I saw for using it with RACSignal was to get the reusability between different signals and being able to construct the transformations separately from connecting the signals in cases where that makes sense.

Did you have a chance to look at the implementation, ie. did it seem to make sense from a RAC point of view?

**Comment by jspahrsummers** [comment]
> the main benefits I saw for using it with RACSignal was to get the reusability between different signals and being able to construct the transformations separately from connecting the signals in cases where that makes sense.

Yup, that makes sense (and sounds great)!

> Did you have a chance to look at the implementation, ie. did it seem to make sense from a RAC point of view?

Without completely digging into all the MOG-specific stuff, the operator implementation looks reasonable. I'd keep an eye on whether all those `concat:`s hamper performance, though.

**Comment by mhallendal** [comment]
> Without completely digging into all the MOG-specific stuff, the operator implementation looks reasonable. I'd keep an eye on whether all those concat:s hamper performance, though.

Thanks a lot! 

Will make sure to keep an eye out and consider alternative approaches if it turns out to be a problem.

**Comment by robrix** [comment]
Very cool work :smile: :+1:

**Comment by mhallendal** [comment]
Thanks Rob! :smile:
