### ISSUE TITLE
Subscribing without any action

### ISSUE THREAD

**Issue by 3-n** [ReactiveCocoa/ReactiveCocoa#1818]
Disclaimer: ReactiveCocoa beginner here ;)

I'm producing a custom signal in my class that has some default side effects via `doNext`. Signal is what I believe is called a cold signal - i.e. it merges underlying signals, performs some processing and returns a new signal. 
In most cases consumers of the class don't have to perform any action besides the default one "happening" inside `customSignal`. However, without subscription via `subscribeNext` signal won't fire. So I end up littering the consumers in:
```objective-c
[[self.property customSignal] subscribeNext:^(id x) {
    // nothing more than default side effect
}];
```
Cannot not subscribe. Cannot subscribe with a nil block. Cannot find any alternative. Trying to wrap my head around this and do it *the right way*. 

Do I have to live with repating that, or is there a better approach? Or maybe I still didn't grok Reactive enough & I'm doing something wrong?

**Comment by adly-holler** [comment]
This situation usually comes up when you're using a ReactiveCocoa but not adopting FRP completely. Have you ever seen the Objective-C warning "Expression result unused – getters should not be used for their side effects" when you have a line like `self.view;`? This is the RAC equivalent. 

The idea behind it is, _somebody_ external to the signal must care about the values it sends. Otherwise why should the cold signal do its work? The side effects of a signal are for internal use and they're not meant to be the ultimate destination of signal events.

To get rid of this, your best bet is probably to refactor a side effect into a subscription, either an explicit subscription (😐) or an implicit one, like a property binding with the `RAC()` macro (🙌). If you could post some more example code, e.g. what side effects we're looking to trigger, I'd be glad to look at it and make suggestions.

**Comment by 3-n** [comment]
Well I tried to build a simple form validation framework, extending the idea of validation used in many tutorials (seemed a good starting point). I'll try to rewrite this to a relatively minimal example ;)

Each `Form` object would be a composition of objects conforming to `ValidableFormPart` protocol like this
```objective-c
@protocol ValidableFormPart <NSObject>
@required
- (RACSignal *)validationSignal; 
- (RACSignal *)currentValidationStatusSignal;
@optional
@property (nonatomic, strong) NSArray *parts;
@end
```
`Form` would also conform so it would give out one set of merged signals, and so I could construct dynamically forms with subforms, composite design pattern style, and abstract away the complexities of validation ;)

`validationSignal` would pass `BOOL`s based on form values. So for example `UITextField` subclass `MYTextField` implementing `ValidableFormPart` would have this, if we would only ever care about text length (in reality I'd have modes for email, password rules, whatever; skipping all that)
```objective-c
- (RACSignal *)validationSignal {
    return [self.rac_textSignal map:^id(NSString *text) {
        return @(text.length > 5 && text.length < 10);
    }];
}
```
This could be used to bind to confirmation button enabled state, filter whether to fire one mode of operation or the other on button action depending on whether form data is valid, etc.

`currentValidationStatusSignal` is about additional information about validation. When there's a need to signal to the user why exactly is this form invalid, i.e. user pressed the "accept this form and send request to API to register my user account", that's when the "empty subscription" occurs. E.g. `MYTextField` could implement it like this:
```objective-c
- (RACSignal *)currentValidationStatus {
    return [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        if (self.text.length < 5) {
            [subscriber sendNext:@"Text is too short"];
        }
        else if (self.text.length > 10) {
            [subscriber sendNext:@"Text is too long"];
        }
        else {
            [subscriber sendCompleted];
        }
    }];
}
```
Parent `ValidableFormPart`-conforming object would then merge these somehow (for example generating a list of validation errors, or just surfacing one most important via `take:1`, anything). I'm skipping that, I feel I'm building a wall of text already ;)

Anyway, based on this, form hierarchy root (i.e. `Form` object) would make available to a controller configuration methods to control the form acceptation flow, i.e. what should happen when user presses the "ok, do stuff" button:
 * `setConfirmationSignal` input, letting `Form` know when user action happens, e.g.
```objective-c
[self.form setConfirmationSignal:[self.okButton rac_signalForControlEvents:UIControlEventTouchUpInside]];
```
`Form` transforms this signal using internal `ValidableFormPart` signals, giving out two external signals
 * `confirmedValidSignal` output, allowing the controller to take action when form turned out to be valid, e.g.
```objective-c
    [[[[self.form confirmedValidSignal] map:^id(id x) {
        return networkRequestSignal;
    }] switchToLatest] subscribeNext:^(id x) {
        [self.navigationController pushViewController:anotherController animated:YES];
    }];
```
 * `confirmedInvalidSignal` that is the problematic one
```objective-c
    [[self.form confirmedInvalidSignal] subscribeNext:^(id x) {
        // here would be showing a validation error message, or highlighting the fields that are wrong with red background, etc.
    }];
```
But the action is mostly the same, or at least has common elements. Let's say most of the time all I want to do is show `UIAlert` with validation message. So `Form` also has `shouldPerformDefaultAction` parameter and if `YES`, then inside `confirmedInvalidSignal` method this happens
```objective-c
    if (self.shouldShowOwnValidationAlerts) {
        confirmedInvalidSignal = [confirmedInvalidSignal doNext:^(NSString *status) {
            UIAlertView *alert = [UIAlert that shows the status];
            [alert show];
        }];
    }
```
It works, but as I wrote earlier, it feels wrong.

I thought sending all the metadata like reference to form part object, status messages, form part user-readable IDs etc. all the time along simple BOOL validation signal is a bit overkill, so I just wanted to only have to ask for all this stuff-fetching once, at the moment when it's really needed. But perhaps I should just rewrite this to use just one signal?

I hope this is clear, I honestly tried my best to be just as brief as needed, but I'm not sure how that went ;)

**Comment by adly-holler** [comment]
OK thanks for the details. Here's my thinking:

"Who presents the invalid alert to the user?" With the current design, the answer varies – in the default case, `Form` presents the alert, but in other cases, the controller presents it. That's why the empty subscription feels so wrong. How 'bout we say "the controller presents the alert" to simplify.

As for handling the default alert style, there's a couple choices, which I've arranged from worst to best:

##### Keep letting `Form` handle default alert presentation

Pros:
- Quick and light

Cons:
- Bad separation of responsibilities –– `Form` is a model object and the alert is a UI thing
- Gets harder if you migrate to `UIAlertController`, since you'll need to provide a presenting view controller
- Subscription should probably end when controller is deallocated, but doesn't
- Nasty weakify-strongify subscription syntax

```objectivec
// Added to Form:
- (void)performDefaultInvalidAlertAction:(NSString *)status {
    /// show the alert view
}
// In controller. NOTE: Use @weakify/@strongify or equivalent to avoid retain cycle
[[self.form confirmedInvalidSignal] subscribeNext:^(id x) {
    [self.form performDefaultInvalidAlertAction:x];
}];
```

##### Add a category method on UIViewController

Pros:
- Good separation of responsibilities

Cons:
- Nasty weakify-strongify subscription syntax
- Subscription should probably end when controller is deallocated, but doesn't

```objectivec
@implementation UIViewController (MYFormValidationAlerts)
- (void)my_performDefaultInvalidAlertAction:(NSString *)status {
    // it's our time to shine
}
@end
// In controller. NOTE: Use @weakify/@strongify or equivalent to avoid retain cycle
[[self.form confirmedInvalidSignal] subscribeNext:^(id x) {
    [self my_performDefaultInvalidAlertAction:x];
}];
```

##### Add a category method on RACSignal

Pros:
- Very clean syntax
- Subscription ends when appropriate
- Lots of room to grow. For example, you could pass `self` into the method and migrate to UIAlertController or automatically dispose of the subscription when self will deallocate.

Cons:
- Might be unfamiliar

```objectivec
@implementation RACSignal (MYFormValidationAlerts)
- (RACDisposable *)performDefaultInvalidAlertAction {
    return [self subscribeNext:^(NSString *status) {
        // do the thing
    ];
}
@end
// In your controller:
[[self.form confirmedInvalidSignal] performDefaultInvalidAlertAction];
```

**Comment by 3-n** [comment]
I feel like implicitly self-subscribing like this is what was missing in my mindset. It's so clean and simple when already discovered :D

Thanks a lot!
