### ISSUE TITLE
Run other signals as a side effect

### ISSUE THREAD

**Issue by 7ynk3r** [ReactiveCocoa/ReactiveCocoa#1881]
I need to be able to use `doNext` with a signal inside, not just a block. The problem is that I use signals for side effects too.

When I do this kind of things my code looks really messy.

For example:

	[httpRequestSignal flattenMap:^(Response *response) {
	    // Save the response.
	    return [[self saveResponse:response] then:^{
	    	// Return the response.
	        return [RACSignal return:response];
	    }];
	}];

I'm tempted to use `first` and make the code look much better, but it looks wrong making a signal synchronous.

	[httpRequestSignal doNext:^(Response *response) {
	    // Save the response.
	    [[self saveResponse:response] first];
	}];

Any advice?

http://stackoverflow.com/questions/29528185/racsignal-donext-with-signals

**Comment by jspahrsummers** [comment]
I definitely wouldn't use `-first` here.

The former example you've shown looks reasonable to me. I think it's appropriate that it takes one or two extra hoops to inject side effects, since I generally discourage them. :wink:

If you wanted to save a bit of indentation, you could replace `-then:` with `-ignoreValues` and `-concat:` (which has the same effect here), but it'll still require that chaining.

**Comment by 7ynk3r** [comment]
Ok, thanks for the response! 
In this case because I have to write the response to a cache, I have no alternative than using a side effect with a signal.

**Comment by jspahrsummers** [comment]
This _is_ a fairly common pattern—one that I've used myself too. Maybe there's some way we could turn it into a reusable operator in the future.

**Comment by 7ynk3r** [comment]
Thanks again Justin for including this as a future enhancement! 
I really love signals and use them a lot!
