### ISSUE TITLE
Is it possible to use ReactiveCocoa with Objective-C++

### ISSUE THREAD

**Issue by bartl-git** [ReactiveCocoa/ReactiveCocoa#1914]
I have several objc++ files in my project. Neither RACObserver nor RACComand do not work in that files.
When I switch file type to pure Objective-C everything works.

Is there any possibilities to resolve this issue in my project.

Thanks.

**Comment by jspahrsummers** [comment]
Can you please be more specific about what's failing, and what you've tried to make it work?

**Comment by bartl-git** [comment]
View controller uses ComponentKit framework which is written on objc++.
For a example, I have this simple line of code:

**Comment by bartl-git** [comment]
View controller uses ComponentKit framework which is written on objc++.
For a example, I have this simple line of code:

`self.navigationItem.rightBarButtonItem.rac_command = self.viewModel.addProjectCommand;`

The command never executes.
Another example:

`
[RACObserve(self.viewModel, projects) subscribeNext:^(id x) {
        // do something
    }];
`

Observe block never executes.

When I remove all ComponentKit functionality and turn file type to pure Objective-C everything works as expected.

**Comment by jspahrsummers** [comment]
At first glance, that doesn't seem related to the choice of language, but who knows. Can you please share a project that demonstrates the issue?

**Comment by bartl-git** [comment]
Ok. I'll try to reproduce the issue in a separate project. Than I'll post here the link.

**Comment by jspahrsummers** [comment]
Thanks!

**Comment by bartl-git** [comment]
Very strange issue for me. It took much time for me to reproduce this one.

https://github.com/bartl-git/ReactiveCocoaAndComponentKitIssue

I remove all unnecessary code, kept only where issue appears.
Central part of project is a ViewController which derived from BaseCollectionViewController.
ViewModel creates test command (attached to the rigthBarButton of ViewController - "test" button) and have property (observingString) which ViewController is observing. As I mentioned in this question command and property observing are not working.

But if i remove the componentDataSource initialization (line 26 in the BaseCollectionViewController.mm) everything starts working.

**Comment by jspahrsummers** [comment]
Is it possible that ComponentKit is responsible for this behavior, and not C++ itself? For example, does it use any runtime manipulation of objects that might collide with Cocoa's KVO facilities?

**Comment by kastiglione** [comment]
@bartl-git:

The `ControllerFactory` is creating a `ViewModel` with `+init` but it should be calling [`+initWithModel:`](https://github.com/bartl-git/ReactiveCocoaAndComponentKitIssue/blob/296931fbe0fa214982a0acc5d4f0fa780573d7c8/ReactiveCocoaAndComponentKitIssue/ControllerFactory.mm#L18). The code that isn't working is failing because `self.model` is `nil`.

**Comment by kastiglione** [comment]
*Ignore the close. I totally mis-answered and mis-read this*.

**Comment by kastiglione** [comment]
Ok, so the problem is that before the initializer assigns to `self.model`, it's referring to `self.collectionView` ([in `BaseCollectionViewController`](https://github.com/bartl-git/ReactiveCocoaAndComponentKitIssue/blob/296931fbe0fa214982a0acc5d4f0fa780573d7c8/ReactiveCocoaAndComponentKitIssue/BaseCollectionViewController.mm#L26)) which necessarily calls `-loadView` and then `-viewDidLoad`. Since `self.model` is `nil`, both the assignment of the command, and the `RACObserve` observation, will do nothing.

To fix this, move the creation of the `CKCollectionViewDataSource` instance to `-viewDidLoad`.
