### ISSUE TITLE
`RACScheduler.schedule` collides with objc implementation

### ISSUE THREAD

**Issue by zdavison** [ReactiveCocoa/ReactiveCocoa#1932]
Using the RAC objc API from Swift seems to present the following issue:

```
    let scheduler = RACScheduler(priority: RACSchedulerPriorityHigh)
    scheduler.schedule{
      NSLog("crashme");
    }
```
This will crash, presumably because there is an obj-c RAC api method called `schedule:` that matches the interface of the Swift one.

This can be worked around by implementing an obj-c category on `RACScheduler` and creating a differently named method to call the obj-c `schedule:` method:

```
- (RACDisposable *)objc_schedule:(void (^)(void))block{
  return [self schedule:block];
}
```

I assume this issue is going to occur a lot, I'd write a fix, but I'm not sure what strategy should be?

**Comment by jspahrsummers** [comment]
Hmm, I'm not really sure why this would be causing problems, since the Swift method should match the type signature of the Objective-C one. Could you perhaps share a sample project?

In any case, you can always just use the Swift schedulers directly from Swift, and call `toRACScheduler` to present a `RACScheduler` interface wherever you need one specifically.

**Comment by jspahrsummers** [comment]
:boot:ing this from the milestone, which will now just contain blocking issues.
