### ISSUE TITLE
How to trigger selector without argument when signal sends next?

### ISSUE THREAD

**Issue by onmyway133** [ReactiveCocoa/ReactiveCocoa#1935]
How to trigger selector when a signal sends next event? This selector does not have any arguments. Like when `items` changed on `ViewModel`, I want to call `reloadUI` on `ViewController`.

I see `rac_liftSelector:withSignals:` is intentionally used for selector with arguments ??

> This helper will “lift” a selector into “signal space” where the selector is invoked anytime the corresponding argument signals send a new value. The signals passed to the rac_liftSelector must match the number of arguments expressed by the selector.

**Comment by Tiger6688** [comment]
why not subscribe the signal directly??
[signal subscribeNext:^(id x){
[self reloadUI]
}];

It might help to start with where lift comes from.

We use it in the sense you might see in Haskell or other statically-typed functional languages:

Lifting is a concept which allows you to transform a function into a corresponding function within another (usually more general) setting. (http://www.haskell.org/haskellwiki/Lifting)
For RAC, we use it to mean that we're lifting a selector in its normal setting into the reactive setting.

If a selector doesn't take any arguments, it must be impure. Which is to say, it uses or effects state outside of the method itself. (Or it could be constant, which is nice but then you could just use -mapReplace:.) Side effects are a reality of Cocoa development, but in RAC we try to make explicit where side effects can happen. Conventionally, it's in the -do*: and -subscribe*: family of operators.

We don't want to allow zero-argument selectors to be lifted because it steers you in the wrong direction. Side effects should be done in one of the designated side effecting operators. Lifts should be pure.

reference:
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1096

**Comment by neilpa** [comment]
Closing, but please re-open if that doesn't answer your question.
