### ISSUE TITLE
Bind a MutableProperty to UITextField in RAC 3

### ISSUE THREAD

**Issue by gabro** [ReactiveCocoa/ReactiveCocoa#1979]
Hi,
sorry for the trivial question, but I'm fairly new to ReactiveCocoa and this is arguably a confusing time since the API are in flux :)

I'm trying to do some MVVM binding a `UITextField` text value to a `MutableProperty` (which ideally would live in a separate `ViewModel` class. Here's what I have so far:

```
import UIKit
import ReactiveCocoa

class ViewController: UIViewController {

  override func viewDidLoad() {
    super.viewDidLoad()
    
    let emailTF = UITextField()
    emailTF.frame = CGRect(x: 10, y: 40, width: 200, height: 50)
    emailTF.placeholder = "foo placeholder"
    
    let email = MutableProperty<String>("")
    
    let emailProducer = emailTF.rac_textSignalProducer()
    email <~ emailProducer
    
    email.producer |> map { println($0) }
    
    self.view.addSubview(emailTF)
  }

}

extension UITextField {
  func rac_textSignalProducer() -> SignalProducer<String, NoError> {
    return self.rac_textSignal().toSignalProducer()
      |> map { $0 as! String }
      |> catch { _ in SignalProducer<String, NoError>.empty }
  }
  
}
```

To my understanding when I bind `email` to `emailProducer`, the latter should start emitting values.
I then try to access the `producer` and `map` over it. Unfortunately it never gets executed.

The only way I ever managed to have something printed in the console was manually starting the producer via

```
emailProducer.start { println($0) }
```

but it kind of defeats the purpose of binding it to a property.

I'm clearly getting something terribly wrong, any idea?

**Comment by MichaelMcGuire** [comment]
There are a couple of issues I see with your code.

The line:
````
email.producer |> map { println($0) }
````

creates a new `SignalProducer` that you are not doing anything with.  You aren't assigning it to a variable to do anything with.  Since you are wanting to perform an action on each new value in your `MutableProperty` (print it to the console), you want to use `start`.  So do something like this:

```
email.producer.start(next: { println($0) })
```

The other problem is that you are not holding a reference to the `MutableProperty` anywhere so it will go out of scope once `viewDidLoad` stops executing.  The binding will not hold a reference to the property.  So for this simple example, make sure to hold a reference in the view controller:

```
class ViewController: UIViewController {
    let email = MutableProperty<String>("")
    // ... rest of code
```
In a real application, the `MutableProperty` would be a public property on your view model, which the view controller would bind to.

Hope that helps.

**Comment by gabro** [comment]
Silly me, the reference going out of scope was causing the misbehavior.

Thanks a lot for the thorough explanation!

**Comment by jspahrsummers** [comment]
Thanks @MichaelMcGuire, for helping out here! :sparkles:
