### ISSUE TITLE
Adding a collectIntoBatches operator

### ISSUE THREAD

**Issue by jjoelson** [ReactiveCocoa/ReactiveCocoa#2003]
Hi,  

I recently needed to create this Signal operator that basically works the same as `collect` except it passes a series of Arrays of the specified batchSize.

``` swift
public func collectIntoBatches<T, E>(batchSize: Int)(signal: Signal<T, E>) -> Signal<[T], E> {
    precondition(batchSize > 0)
    
    return Signal { observer in
        var batch = [T]()
        batch.reserveCapacity(batchSize)
        
        return signal.observe(next: { value in
            batch.append(value)
            if batch.count >= batchSize {
                sendNext(observer, batch)
                batch.removeAll(keepCapacity: true)
            }
        }, error: { error in
            sendError(observer, error)
        }, completed: {
            // Send the final batch if necessary.
            if !batch.isEmpty {
                sendNext(observer, batch)
            }
            sendCompleted(observer)
        }, interrupted: {
            sendInterrupted(observer)
        })
    }
}
```
I thought I'd share it here in case there's interest in adding it to RAC. I'm not sure if I should have just created a pull request instead of creating an issue, so let me know if posting this as a pull request better fits the project's workflow.

**Comment by jspahrsummers** [comment]
Thanks for sharing! For future, we're always happy to review pull requests. :sparkles:

In this particular case, though, I don't know if we can justify increasing the API surface further. It seems like a somewhat uncommon use case, so it might unnecessarily confuse users who are trying to do something similar.

FWIW, you may also find `scan()` to be of use here, because it allows you to accumulate an array like that without having to manipulate a stateful variable.

**Comment by jjoelson** [comment]
Thanks for the tip on `scan()`.
