### ISSUE TITLE
How to catch an error and map in RAC 3?

### ISSUE THREAD

**Issue by s0mmer** [ReactiveCocoa/ReactiveCocoa#2036]
I'm aware that I'm able to catch an error on a `SignalProducer` using `catch`. However, the implementation of `catch` does not allow me to transform the type of the value, only the type of the error. How would it be possible to change the type of the value when an error occurs?

**Comment by neilpa** [comment]
Check out [`mapError`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/6710e0f44f7efe40d9fe7731f6f205b50bb96d16/ReactiveCocoa/Swift/Signal.swift#L147-L148)

**Comment by jspahrsummers** [comment]
@s0mmer You can't manipulate the value type with `catch` because the happy path and the bad path need to match types, for the simple reason that all handlers _afterward_ are expecting values of the original type.

This is mildly annoying when you _know_ that an error will occur, but that's a minority of cases. Most real world code can error or send a value, so downstream consumers need to know a single type of value to expect.

If you really need to leave `catch` with a different value type, I'd create or use a type like [`Either`](https://github.com/robrix/Either), where one side represents the good (non-caught) case and the other side represents the bad (caught error) case.

**Comment by s0mmer** [comment]
Thanks for clarifying this @jspahrsummers :thumbsup:

**Comment by jspahrsummers** [comment]
No problem!
