### ISSUE TITLE
Removing Disposable

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#2044]
`Disposable`s in general, but especially the management of them in signal/producer lifetimes, feel like kind of a hack now that we have a proper `.Interrupted` event.

It’s probably too late to do anything about this for RAC 3, but maybe we should rethink what disposal means for future releases.

Thoughts?

/cc @nomothetis @andymatuschak

**Comment by nomothetis** [comment]
Sorry, I was on vacation.

I think this is conceptually a great idea. I'd have to think carefully about the problems they solve and how `.Interrupted` responds to them to see what the real cost would be, though.

**Comment by neilpa** [comment]
We should experiment with this for RAC 4 and see how well it works.

**Comment by NachoSoto** [comment]
I'd still love to consider this, but how does everyone feel about bumping it out of the initial `4.0` release?

**Comment by andymatuschak** [comment]
Agreed.

**Comment by neilpa** [comment]
> I'd still love to consider this, but how does everyone feel about bumping it out of the initial 4.0 release?

My plan was to take a first crack at this either this weekend or next week so I'd like to keep it for now.

**Comment by neilpa** [comment]
I'd also like Xcode 7.1 to GM and stabilize before we attempt to finalize 4.0 given all the other shit it broke.

**Comment by NachoSoto** [comment]
@neilpa how do you feel about this? what do you think about leaving it for `4.1`?

**Comment by neilpa** [comment]
I explored this some about a month ago. I didn't get very far and it's going to take more serious thought and work to pull off. I'm fine delaying it assuming we can figure out other workarounds for the `flatten` disposal bugs.

**Comment by NachoSoto** [comment]
:+

**Comment by andersio** [comment]
I have tried to put together a prototype. But my assumption is that the only replacement to `Disposable` _once and for all_ would be circular signals in `Signal.observe`, which would be extended to accept a `trigger` that can dispose of the signal.

The most important tidbit is that `Signal.observe` would no longer return a "detacher", which is crucial to the entire lifetime management model. The top-to-bottom `interrupted` wouldn't help here, because detaching an observer is an action in a reverse direction.

**Comment by mdiep** [comment]
Closing this since it's now a ReactiveSwift issue, not a ReactiveCocoa one.
