### ISSUE TITLE
fold

### ISSUE THREAD

**Issue by NebulaFox** [ReactiveCocoa/ReactiveCocoa#2047]
I was trying to go through an array but wanted the next value as well, like

    let array = [1, 2, 3, 4]
    
    // create a signal from the array
    signal.observer { tuple in
        println(tuple)
    } 
    // (1, 2)
    // (2, 3)
    // (3, 4)

The closest I could find was `scan` but that required me to give an initial value. I sort of expected something like fold.

**Comment by mdiep** [comment]
I think you're looking for `combinePrevious`.

**Comment by NebulaFox** [comment]
`combinePrevious` is not what I want. It requires an initial value. It's name in a bit confusing since `combineLatest` deals with combining signals.

I'm looking for something like http://reactivex.io/documentation/operators/buffer.html

**Comment by jspahrsummers** [comment]
You can provide a meaningless initial value and then simply filter out the event that contains it.

Most variants of fold (which this doesn't even seem to be) require a starting argument, because otherwise the behavior on empty or single-element sequences is undefined.

`Buffer` is an altogether different operator, and the example given in the issue body could not be accomplished with buffering.

**Comment by neilpa** [comment]
Closing, but re-open if that doesn't answer your question.
