### ISSUE TITLE
Easy to deadlock a MutableProperty

### ISSUE THREAD

**Issue by joshaber** [ReactiveCocoa/ReactiveCocoa#2124]
Consider:

ViewControllerA is initializing. Its `-viewDidLoad` does something like: 

```swift
someViewModel.someMutableProperty.producer.start(next: { _ in
    let visible = viewControllerB.view.superview != nil
    // ... other stuff ...
})
```

Accessing `viewControllerB`s `view` property causes it to load its view.

ViewControllerB's `-viewDidLoad` does something like:

```swift
someViewModel.someMutableProperty.producer.start(next: { _ in
    // ... cool stuff, probably ...
})
```

:boom: we deadlock in `SignalProducer.buffer` because it's recursively sending events.

This _feels_ weird. Both classes are doing seemingly reasonable things, neither is doing anything wrong. But the combination is Real Bad.

**Comment by bhowell2** [comment]
I believe this is a similar situation to #2100 ?

**Comment by ikesyo** [comment]
Closed by #2147.

**Comment by filwag** [comment]
Consider two scenarios:
```swift
let propertyA = MutableProperty<Int>(4)
let propertyB = MutableProperty<Int>(2)

// Scenario 1
propertyA.producer.start(next: { _ in
    propertyA.producer.start()
})

// Scenario 2
propertyA.producer.start(next: { _ in
    propertyB.producer.start(next: { _ in
        propertyA.producer.start()
    })
})
```

Scenario 1 is not a deadlock anymore (#2147). Scenario 2 leads to a deadlock: outer `next` is executed on `propertyA`'s buffer queue, `propertyB.producer.start()` synchronously dispatches us to `propertyB`'s buffer queue and finally `propertyA.producer.start()` being on a queue different from `propertyA`'s buffer queue synchronously dispatches to `propertyA`'s buffer queue again and we're deadlocked. Is this an expected behaviour?

Thanks

**Comment by jspahrsummers** [comment]
Scenario 2 should not deadlock. Can you please file an issue with a reproducible case?
