### ISSUE TITLE
RAC 3: Generic protocol actions?

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2135]
I'd be great to be able to create a generic protocol like this:
```Swift
protocol RACFetchable {
	typealias I      // input type for fetchAction
	typealias O    // output type for fetchAction
	var fetchAction : Action<I, O, NSError> {get}
}
```
Then in some class:
```Swift
init(fetchable: RACFetchable) ...
```

Xcode segfaults when attempting that though, complaining about generic constraints. 
`protocol 'RACFetchable' can only be used as a generic constraint because it has Self or associated type requirements`

Anyone have any ideas on coercing Xcode to accept a generic action?

**Comment by ikesyo** [comment]
Something like that?

```swift
class FooBar<In, Out> {
    let action: Action<In, Out, NSError>

    init<T: RACFetchable where T.I == In, T.O == Out>(fetchable: T) {
        action = fetchable.fetchAction
    }
}

// or

class FooBar<T: RACFetchable> {
    let action: Action<T.I, T.O, NSError>

    init(fetchable: T) {
        action = fetchable.fetchAction
    }
}
```

**Comment by memmons-ntst** [comment]
@ikesyo Interesting, thanks for the input! Unfortunately that approach is too restrictive. RACFetchable represents a view model that is being passed to a view controller. The VC shouldn't know anything about the inputs or outputs required by the view model, just how to bind to the model. So moving those generics to the VC seems like a code smell to me.

Instead of FooBar, think of a `BaseViewController` that you pass view model which is then used to populate the view controller UI -- something like:
```Swift
viewModel.fetchAction.values
|> observeOn(UIScheduler())
|> observe(next: {[weak self] _ in self?.tableViewController.tableView.reloadData()})
```

BaseViewController shouldn't know or care about the input payload or output payload RACFetchable is using to perform fetches. It just cares that it has a `fetchAction` to bind to. Similarly, the view model should not be passed the input payload or output payload.

**Comment by neilpa** [comment]
> The VC shouldn't know anything about the inputs or outputs required by the view model, just how to bind to the model

This doesn't make sense to me. How do you expect it to know how to do the binding without knowing the types? Your example only works because it's explicitly ignoring the values.

**Comment by bhowell2** [comment]
I agree with @neilpa.  Typically the VM doesn't know anything about the VC. Not the other way around. The VM does whatever it wants and the VC binds to it, knowing what the VM needs as an input and what it returns. This helps you create a logic base that is mostly platform independent. *(There may be cases where you'll have to break this, but I haven't encountered any as of yet. And obviously this just depends on your design. I've seen implementations of MVVM where the VM does know about the views - this breaks platform independence though and should probably be avoided. It could also create some retain cycles if they reference each other.)* It may even be more of a code smell that you're ignoring types - it's probably not very clear to other developers what's going on.

On another note, I mainly came across this due to what may be a compiler issue (?) or my lack of understanding:

```Swift

protocol ParentProtocol {
    
}
    
class ChildClassA: ParentProtocol {
        
}

class ChildClassB: ParentProtocol {
        
}

var action: Action<String, ParentProtocol, NSError> = Action() {
    (input: String) -> SignalProducer<ParentProtocol, NSError> in
    return SignalProducer<ChildClassA, NSError> {
        sink, _ in
        sendNext(sink, ChildClassA())
        sendCompleted(sink)
    }
}
// Producing: Cannot find an initializer for type 'Action<Input, Output, Error>' that accepts an 
// argument list of type '((String) -> SignalProducer<ParentProtocol, NSError>)'
```
*Note: This goes for protocol implementation AND class inheritance.*

The above is actually just a very explicit example that can be overcome by ignoring the generic specification on the return of `SignalProducer<ChildClassA, NSError>` - however where I really run into trouble with this is calling functions that must explicitly return a `SignalProducer<ParentProtocol, NSError>`. Then a similar the error will show: `'SignalProducer<ChildClassA, NSError>' is not convertible to 'SignalProducer<AnyObject, NSError>'`

Maybe this is intentional and the easy solution is to create explicit actions and methods for each different type, but this quickly becomes verbosely redundant. Any thoughts or suggestions?

**Comment by memmons-ntst** [comment]
@neilpa @ikesyo Putting aside for a moment how much the VC should know about the innards of the parts of the data model that is *tangential* to the concerns of the UI -- I still assert that, _at least for the specific design I am looking at_, the VC having too much knowledge about the model is bad, but let's move on -- what is the practical implementation that avoids segfaults? Maybe I misunderstood how the example given by @ikesyo maps to my example. I thought it would be as follows, but Xcode still segfaults. Note this is running on Xcode 6.3.2 and Swift 1.2. Not sure if that makes a difference.

```Swift
protocol SomeProtocol {
    typealias FetchInput   
    typealias FetchOutput
    var fetchAction : Action<FetchInput, FetchOutput, NSError> {get}
}

class SomeViewController:<T: SomeProtocol>: UIViewController {
    let someObject: SomeProtocol<T.FetchInput, T.FetchOutput, NSError>

    init(someObject: T) {
        self.someObject = someObject
}

```

**Comment by neilpa** [comment]
Generic classes can't have obj-c classes as their base so the above won't work. You should get a compiler error to that effect but you also have a syntax error -- the extra color between SomeViewController and the generic param.

**Comment by memmons-ntst** [comment]
The syntax error was a typo when copying over. I didn't consider that objc base types cannot use generic classes when considering this design. That destroys any possible implementation of a generic view model for view controllers either via protocols or subclasses since any property storing the generic object would need to specify the constraints, which would then require a constraint on the view controller, which can't be done.

:-[

**Comment by neilpa** [comment]
You may be able to do something with `CocoaAction` since that isn't generic. But that would essentially require a static input at initialization time and ignored output.
