### ISSUE TITLE
combineLatest with a Signal & SignalProducer

### ISSUE THREAD

**Issue by MichaelMcGuire** [ReactiveCocoa/ReactiveCocoa#2150]
I'd like use combineLatest or combineLatestWith using a `Signal` and `SignalProducer` but it appears the way the `lift` function works, you can only combine with another `SignalProducer`.  Is there any way to accomplish this with the existing operators?

**Comment by jspahrsummers** [comment]
You can use `SignalProducer.startWithSignal` to obtain a signal for combining. I wouldn't recommend going the other direction.

**Comment by MichaelMcGuire** [comment]
Easy enough, thanks for the help!

**Comment by zdavison** [comment]
In this case, assuming all I want to do is start a producer once and grab a handle on a signal, is this sensible?

```
      var totalWeightSignal: Signal<Weight, NoError>!
      totalWeight.producer.startWithSignal{
        (signal, disposable) in
        totalWeightSignal = signal
      }
```

it seems a little odd, since really i'd prefer to do this with a blocking call like:

```
var totalWeightSignal: Signal<Weight, NoError> = totalWeight.producer.start()
```

I get why the API is like this for `SignalProducer`s in general, but in the case of `MutableProperties`, it makes the API a little difficult for use with `combineLatest`, I'm sure I'm missing some subtleties here, a `MutableProperty` seems idiomatic to a `RACReplaySubject(capacity: 1)` to me, and since that concept is now replaced by `SignalProducer`s, that could be the reason this is this way?

**Comment by schickling** [comment]
+1

**Comment by aventurella** [comment]
+1 as well

**Comment by iandundas** [comment]
+1

**Comment by jspahrsummers** [comment]
Please do not +1 issues. If you would like to see something happen sooner, a pull request is the best argument.

**Comment by NachoSoto** [comment]
A new API was introduced recently to instantiate a `SignalProducer` with a `Signal`, and no side effects `SignalProducer(signal:)`. That might be what you want for this :)

**Comment by iandundas** [comment]
Thanks! And you're right, sorry - though it was +1 to the question, not to a feature request.
