### ISSUE TITLE
RACObserve on UISearchBar's text

### ISSUE THREAD

**Issue by phiphuc89** [ReactiveCocoa/ReactiveCocoa#2175]
My code is 

```objectivec
[RACObserve(self.searchBar, text) subscribeNext:^(NSString* text) {
        NSLog(@"Text: %@", text);
}];
```
never called.

When I add rac_textsignal to searchBar

```objectivec
- (RACSignal *)rac_textSignal {
    self.delegate = self;
    RACSignal *signal = objc_getAssociatedObject(self, _cmd);
    if (signal != nil) return signal;
    signal = [[self rac_signalForSelector:@selector(searchBar:textDidChange:) fromProtocol:@protocol(UISearchBarDelegate)] map:^id(RACTuple *tuple) {
        return tuple.second;
    }];
    objc_setAssociatedObject(self, _cmd, signal, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    return signal;
}
```
I can get searchBar's text, but it isn't working when I set text programmatically
```objectivec
[self.searchBar setText:@"test"];
```

How can I get searchBar's text whenever it changed? Thank you.

**Comment by phiphuc89** [comment]
My problem solved

```objectivec
[[RACSignal merge:@[self.searchBar.rac_textSignal, RACObserve(self.searchBar, text)]] subscribeNext:^(NSString* text) {
        NSLog(@"Text: %@", text);
}];
```
Because previously, I printed text by
```objectivec
 NSLog(@"Text: %@", text);
```
so if text is "", the console doesn't print it.

**Comment by brow** [comment]
UIKit classes generally aren't KVO-compliant for their properties, which is why `RACObserve(self.searchBar, text)` doesn't work.

FWIW, the `rac_textSignal` defined by RAC2 on `UITextField` and `UITextView` deliberately doesn't send for programmatic changes: http://stackoverflow.com/a/20187373. If you really need that behavior, I think using `merge` is a good solution.

However, given that `RACObserve(self.searchBar, text)` doesn't send, I don't understand why your solution in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2175#issuecomment-121477414 works...
