### ISSUE TITLE
[Question] combineLatest

### ISSUE THREAD

**Issue by aputinski** [ReactiveCocoa/ReactiveCocoa#2258]
I'm trying to find the ReactiveCocoa 3.0 / Swift equivalent of this pattern from previous versions of ReactiveCocoa:

```objectivec
RAC(self.submitButton, enabled) = [RACSignal 
  combineLatest:@[siteAddressValidSignal, accessKeyValidSignal] 
  reduce:^id(NSNumber *siteAddressValid, NSNumber *accessKeyValid){
    return @(siteAddressValid.boolValue && accessKeyValid.boolValue);
}];
 ```

It appears that `reduce` now only fires when all signals have completed?

**Comment by neilpa** [comment]
That's how `reduce` always works, although I can see the confusion since the RAC 2 version is poorly named. Should probably be `-[combineLatest:map]` instead of `[combineLatest:reduce]`. That's what you would want in RAC 3 though -- `combineLatest(addressValid, keyValid) |> map { address, key in address && key }`.

**Comment by aputinski** [comment]
Thanks!
