### ISSUE TITLE
[Question] Type Signature Error in one file and not the other

### ISSUE THREAD

**Issue by jeffreybergier** [ReactiveCocoa/ReactiveCocoa#2265]
Hi, I have quite an odd issue. I was building two specific methods that perform a bunch a bunch of work and I was doing it in a nstablecellview. As the logic got bigger I wanted to move it to a dedicated class. I literally copied and pasted the code and changed the self. behavior to a self.delegate behavior.

I have tried a bunch of stuff, but I cannot get swift to compile the new file. I tried deleting all start code and changing it to () and I get a slightly different error. I have to delete everything including the flatmap to get it to work. I also tried adding the explicit return type in the flatmap closure. That didn't help. I tried clearing the derived data. I restarted the computer.

The files are here:
working file: https://github.com/jeffreybergier/Cartwheel/blob/master/Cartwheel/Cartwheel/CartListTableView/CartListTableCellViewController.swift
broken file: https://github.com/jeffreybergier/Cartwheel/blob/master/Cartwheel/Cartwheel/CartfileUpdater.swift

and see this screenshot below for a visual. 

Thanks in advance. Any help is greatly appreciated.
– Jeff

<img width="1439" alt="buildissue" src="https://cloud.githubusercontent.com/assets/7349616/9290182/cacd337c-433d-11e5-8a4a-dab2c2a863fa.png">

**Comment by ikesyo** [comment]
That is because the [`start()`](https://github.com/jeffreybergier/Cartwheel/blob/6b381796ffbbb1367088ae300f9f2882f2a47b32/Cartwheel/Cartwheel/CartfileUpdater.swift#L50-L52) method in your `CartfileUpdater` conflict with ReactiveCocoa's `public func start<T, E>(error: (E -> ())? = nil, completed: (() -> ())? = nil, interrupted: (() -> ())? = nil, next: (T -> ())? = nil)`. You should rename the method not to conflict.

**Comment by jeffreybergier** [comment]
wow. derp. that was so simple. thanks a lot.
