### ISSUE TITLE
[Question] (swift2) - NSButton and Action

### ISSUE THREAD

**Issue by mobilinked** [ReactiveCocoa/ReactiveCocoa#2280]
There is no problem if I use RAC_Command to link with NSButton click event. I'd like to try link "Action" and NSButton via CocoaAction, but it does not work

(it's NSButton for OSX, not UIButton for iOS) 
----------------------------- 
```
class ViewModel {
    lazy var startAction: Action<String, Void, NoError> = {
        return Action { _ in
            print("clicked") 
            return SignalProducer<Void, NoError>.empty
        }
    }()
}

private var button: NSButton! 
let viewModel = ViewModel() 
setupBind() {
    self.button.target = CocoaAction(viewModel.startAction, input: "")
    self.button.action = CocoaAction.selector
}
```
------------- 
The problem is that after button be clicked, action is not fired.

**Comment by ikesyo** [comment]
I think this is because the created `CocoaAction(viewModel.startAction, input: "")` are not strongly referenced anywhere (`NSControl.target` is an weak property), so the action is deallocated immediately. You should hold the action somewhere, for example in your view model or set the action to `Action.unsafeCocoaAction` property.

**Comment by mobilinked** [comment]
@ikesyo it works, thanks.
