### ISSUE TITLE
[Question] Send error to existing RACSignal

### ISSUE THREAD

**Issue by JeanLebrument** [ReactiveCocoa/ReactiveCocoa#2306]
Hello,

I'm a beginner in FRP and ReactiveCocoa as well.

I have a class that has a getter on a `RACSignal` which sends the class's state.

    struct ManagerState {
      var busy: Bool
    }
    
    public func RACObserve(target: NSObject!, keyPath: String) -> RACSignal {
      return target.rac_valuesForKeyPath(keyPath, observer: target)
    }
    
    class Manager {
      internal var managerState: ManagerState
      internal var signal: RACSignal
      
      init() {
        managerState = managerState(busy: false)
        signal = RACObserve(self, "managerState")
      }
      
      func observable() -> RACSignal {
        return signal
      }
      
      func changeState() {
        /* 
        if something_bad {
          send error to signal attribute.
        }
        */
      }
    }

Then the client class which uses the `Manager` class subscribes on the `Signal` returned by the `observable()` method.

I look for a way to send error to the `signal` attribute.

Any suggestion?
Thanks!

**Comment by iandundas** [comment]
Hey - first thing which jumps out at me is that you're using the Objective-C API from within Swift (classes prefixed with RAC are the 'legacy' versions, and shouldn't generally be used for new apps now.)

Secondly, Signals are one-way streams, so they transport next/error/complete events - but you can't send events back up the chain.

A style tip: you might like to store "Busy" (and whatever other state you have, e.g. Online) in `MutableProperty`s instead of in a struct - and then you can derive your overall state from combining these signals together using something like:

```swift
    let busyProperty = MutableProperty<Bool>(false)
    let onlineProperty = MutableProperty<Bool>(false)
    
    let managerStateSignalProducer: SignalProducer<Bool, NoError>
    
    init() {
        managerStateSignalProducer = combineLatest(busyProperty.producer, onlineProperty.producer) |> map {(isBusy, isOnline) in return isBusy && isOnline}
        managerStateSignalProducer.start(next: { receivedValue in
            if receivedValue{
                // manager is ready
            }
            else{
                // manager is not ready
            }
        })
    }
```

With regards to sending errors back to the Manager, your manager could be subscribed to a SignalProducer on the client class, which would send error events. There are other ways to do it - maybe someone else can recommend techniques.

Recommended reading: [http://nomothetis.svbtle.com/an-introduction-to-reactivecocoa](this) and the [follow-up](http://nomothetis.svbtle.com/reactivecocoa-ii-reacting-to-signals)

**Comment by JeanLebrument** [comment]
Thanks for your help!
