### ISSUE TITLE
[Question] Do Signals have a flatten operator in 3.0?

### ISSUE THREAD

**Issue by jduenas** [ReactiveCocoa/ReactiveCocoa#2314]
From what can I tell only SignalProducers can use that operator.  Is there a way to flatten a Signal that streams SignalProducers/Signals?  I'm using the Swift2 branch btw.

**Comment by neilpa** [comment]
There was briefly but only for signals-of-producers. Signals-of-signals are problematic since you could miss events on the inner signal. Note, this is a general problem for any operator where the value type is a signal so we don't want to encourage that pattern.

I mentioned briefly above because we removed them after discovering crashes related to lifting the signal-of-producers operators to producers-of-producers. We speculated that this was a Swift 1.2 compiler bug. Saw some instances manifest in Carthage. We were never able to track down the cause for find a workaround so reverted `flatten` to only producers-of-producers.

That said, we should try to bring these back in the Swift 2 branch. I've had a couple instances where mapping a hot signal of "work" into serialized producers could've used this operator.

**Comment by jduenas** [comment]
Thanks for the reply. I see your point on missed events on the inner signal. But I can see it being useful in some cases such as a search box that streams a SignalProducer for network calls. 

For now, I was able to get similar functionality by subscribing to the signal inside of a SignalProducer and just doing a flatten on that. 

Thanks again!

**Comment by neilpa** [comment]
I've opened #2315 to track this

**Comment by NachoSoto** [comment]
I just opened #2422 with a similar question.

**Comment by neilpa** [comment]
> Isn't that true with any Signal though?

Yes, but when it's affectively indirected it could still be more confusing since you don't see the inner subscribe.

> What's exactly the thing that we wouldn't want to encourage?

Well `.Concat` doesn't work for this.

**Comment by NachoSoto** [comment]
> Well `.Concat` doesn't work for this.

Oh, of course! Would it make sense to add only `merge` then?
```swift
extension SignalType where Value: SignalType, Error == Value.Error {
    public func merge() -> Signal<Self.Value.Value, Self.Error>
}
```

**Comment by neilpa** [comment]
I don't like the inconsistency with `flatten(strategy)`. Maybe we go back to separate operators, but that would require 3 implementations of `merge` since `SignalProducerType` isn't defined in terms of `SignalType`. I'm starting to feel like we're missing a primitive since we don't have HKTs but that starts to introduce new complexity which I'm also weary of.

**Comment by neilpa** [comment]
And following down that path may end up with something close to `RACSignal`, `RACStream` and `RACSequence` all over again. Although at least this time I think we picked a better split with hot/cold instead of push/pull.

**Comment by neilpa** [comment]
@jspahrsummers Any insight to add here?

**Comment by neilpa** [comment]
Thinking out load some more, maybe it would be nice to have an `EventStream` protocol that both `SignalType` and `SignalProducerType` are defined in terms of. However, that probably requires a `Self` type constraint which starts to make things messy.

**Comment by NachoSoto** [comment]
`Signal`'s `merge` could be implemented in terms of `SignalProducer`'s though:
```swift
signals.flatMap(.Merge) { (signal) -> SignalProducer<T, E> in
	return SignalProducer { observer, disposable in
		disposable += signal.observe(observer)
	}
}
```

I think that's correct?

**Comment by neilpa** [comment]
In lieu of a shared base protocol we might be able to do a [converter protocol](https://github.com/antitypical/Result/pull/86#issuecomment-142400985).

**Comment by neilpa** [comment]
That merge looks correct, but I'm not sold on offering a built-in operator that goes from hot -> cold since we can't make the same level of guarantees about correctness and consistency.

**Comment by NachoSoto** [comment]
Makes sense.
I think I'm going to keep that as an extension then :+1:

**Comment by jspahrsummers** [comment]
Personally, I think we should have `merge` over `Signal`s.

@neilpa Not sure what you mean about "hot to cold," though.

**Comment by neilpa** [comment]
I meant wrapping a hot `Signal` in a cold `SignalProducer` without explicit semantics around buffering or dropping events.
