### ISSUE TITLE
RAC3 = Swift 1.2 and RAC4 = Swift 2

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2327]
~~Having not shipped v3.0 final and assuming Xcode 7 GM's today, I propose changing our target to Swift 2. We can keep around the existing `RC.1` release and move that code to a `swift-1.2` branch. When we're ready to cut an `RC.2` we can merge `swift2` into `master` (_should_ be soon™). If we need to backport fixes to 1.2 we can always release an `RC.1.1` w/out breaking semver.~~

It's going to be cleaner if we just split major versions of RAC along the Swift version boundary. So RAC3 will target Swift 1.2 and RAC4 will target Swift 2. Going forward we'll only be backporting fixes to RAC3 on demand and future development will be on RAC4.

@ReactiveCocoa/reactivecocoa Thoughts?

**Comment by NachoSoto** [comment]
I'm in. I don't think any of us will have much time to maintain the Swift 1.2 version anyway.

**Comment by neilpa** [comment]
Also, the docs are mostly in sync with the changes in that branch. The only thing I know that's missing is updating the changelog for 1.2 -> 2.0.

**Comment by ikesyo** [comment]
:+1: for the direction, and also we should use lowercase `rc` for tagging in favor of https://github.com/CocoaPods/cocoapods.org/issues/185#issuecomment-123419140.

**Comment by kastiglione** [comment]
Why not? :+1:

**Comment by brow** [comment]
We did [tell users](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-RC.1):

> With this release candidate, RAC 3.0 is API stable, and all of our desired documentation is in place. Please report any bugs you may find!

> Breaking changes may still be made if absolutely necessary, but—for all intents and purposes—this is the API we intend to ship.

If I may be obtuse, what's the downside of incrementing the major version to 4? I agree that people probably wouldn't find time to maintain RAC 3.

**Comment by neilpa** [comment]
> If I may be obtuse, what's the downside of incrementing the major version to 4?

I'm not against this. Although it may be confusing to release v3 and turnaround a week later with a v4-alpha release. In practice, we're effectively doing the same thing. It's just a matter of labeling the releases and communicating that appropriately.

**Comment by brow** [comment]
I suppose I don't lean either way; both approaches seem slightly confusing to humans, and neither approach is confusing to dependency managers. So, :+1: for incrementing the RC number.

**Comment by neilpa** [comment]
Than it comes down to which is worse. Going back on the earlier rc1 statement or releasing a v3 that we immediately deprecate?

**Comment by kastiglione** [comment]
Aren't RAC 3 users the bleeding edge type, the folks that would be eager to upgrade to Swift 2. If so, moving to support Swift 2 is helping them out :stuck_out_tongue_winking_eye:

**Comment by mdiep** [comment]
Given that upgrading to Swift 2 is complicated (especially since it's tied to particular versions of Xcode and OS X), I'd be in favor of releasing the Swift 1.2 code as RAC 3 and Swift 2 as RAC 4. Versions don't mean that much apart from the semantic versioning anyway, and this would give people the possibility of backporting fixes to RAC 3 in necessary.

But that's a pretty weak opinion, and I'm not to invested in it either way. :smile:

**Comment by neilpa** [comment]
> and this would give people the possibility of backporting fixes to RAC 3 in necessary.

Technically this is still possible with the proposed RC.1.1 strategy but definitely more confusing. And now I'm leaning toward RAC3 = Swift 1.2 and RAC4 = Swift 2. It's a clear demarcation and if we do have to back port a fix maintaining a special embedded RC version is going to suck.

**Comment by robb** [comment]
> I'd be in favor of releasing the Swift 1.2 code as RAC 3 and Swift 2 as RAC 4.

:+1:

**Comment by neilpa** [comment]
Talked with @jspahrsummers about this and he's cool with the splitting major RAC versions along the Swift versions. I'll cut v3.0 this weekend and making sure docs are updated to reflect this.

**Comment by NachoSoto** [comment]
:+1:

**Comment by ikesyo** [comment]
:+1:

**Comment by amccarri** [comment]
Hey guys, not sure if this is the appropriate place to comment on this issue or not but wanted to ask about what the time line is for Swift 2.0 support.  My concern is that RAC 3.0 shipped at about the same time as XCode 7 -- yet RAC 3.0 does not support Swift 2.0.  My prediction is that nobody will use RAC 3 since that requires them staying on XCode 6.4.  I'm kind of the RAC evangelist at my company and I feel I'm in kind of a tight spot, with my choices being: a) stick with RAC 2.5, b) tough things out with the swift 2 branch, c) switch to RxSwift.  If I interpret this thread correctly, my current plan is to stick with RAC 2.5 until RAC 4 comes out.

**Comment by NachoSoto** [comment]
Many of us are already using (what's going to be come) RAC 4. Even though it will take a while for it to be officially labeled as "ready for production", it's very much ready to be used :)

**Comment by amccarri** [comment]
Okay cool.  Is that the Swift 2 branch then?  And thanks for the feedback.

**Comment by neilpa** [comment]
Yea, the `swift2` branch for now. I'm working on updates to the changelog to maybe get out an initial RAC4 alpha tonight.
