### ISSUE TITLE
sendCompleted on started cause Interrupted instead of Completed.

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2329]
I am not sure what is an intentional behavior, but currently with a following setup signal is Interrupted. My understanding that Completed was send after producer started, so signal should complete successfully.

```
let signalPipe = Signal<Void, NoError>.pipe()
let signalProducer: SignalProducer<Void, NoError> = SignalProducer { (sink, disposable) in
        let internalDisposable = signalPipe.0.observe(sink)
        disposable.addDisposable(internalDisposable)
    }

signalProducer
    |> on(started: {
        sendCompleted(signalPipe.1)
    })
    |> on(event:{ e in println("event \(e)")} )
    |> start()
```

Is it expected behavior?

**Comment by nikita-leonov** [comment]
Apparently replacement of SignalProducer constructor with buffer call changes this behavior to expected. But it does not answer why setup above is misbehave.

**Comment by jeremiegirault** [comment]
Similar issue with RC.1 and SignalProducers. Makes the app crash. Will write a project which reproduces.

**Comment by jeremiegirault** [comment]
https://github.com/jeremiegirault/rac-bug

**Comment by jeremiegirault** [comment]
I added a new startOn issue in the sample. See AppDelegate

https://github.com/jeremiegirault/rac-bug/blob/master/rac-bug/AppDelegate.swift#L23

**Comment by ikesyo** [comment]
This is an expected behavior. In your example, you terminate the source signal by `sendCompleted(signalPipe.1)` in `on(started: { ... }` closure before starting the producer. The closure is actually called before the produced signal is started. Then, observing a terminated signal would receive an `.Interrupted` event immediately: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v4.1.0/ReactiveCocoa/Swift/Signal.swift#L122-L124

> Observes the Signal by sending any future events to the given observer. **If
the Signal has already terminated, the observer will immediately receive an
`Interrupted` event.**

Closing.
