### ISSUE TITLE
How to subscribe struct CLLocationCoordinate2D

### ISSUE THREAD

**Issue by sarunw** [ReactiveCocoa/ReactiveCocoa#2416]
I have `Place` object with coordinate.
```
@interface Place : NSObject
@property(nonatomic, assign) CLLocationCoordinate2D coordinate;
@end
```
I try to subscribe, but don't know how should I do it.

```
        [RACObserve(self.place, coordinate) subscribeNext:^(CLLocationCoordinate2D coordinate) {
            
        }];
```

This line cause a compile error. I try to debug and seem some NSConcrete... is return, don't know how to unpack it.

**Comment by iv-mexx** [comment]
This is because `CLLocationCoordinate2D` is a primitive struct, so RAC packs it in a `NSValue`. 
You'll have to manually get the coordinate out of the value:

```ObjC
 [RACObserve(self.annotation, coordinate) subscribeNext:^id (NSValue *coordinateValue) {
    CLLocationCoordinate2D coordinate = coordinateValue.MKCoordinateValue;
    // Use the coordinate
}];
```

Not that if you want to return a `CLLocationCoordinate2d` (or any other struct or primitive value) e.g. when using `map`, you'll have to re-pack them into an NSValue or NSNumber yourself.
