### ISSUE TITLE
RAC 4: How to bind Action.executing to UIButton.enabled

### ISSUE THREAD

**Issue by smiLLe** [ReactiveCocoa/ReactiveCocoa#2455]
My current implementation: 

```swift
    let dynProp = DynamicProperty(object: self.button, keyPath: "enabled")
      
      action.executing.producer.start { event in
        switch event {
          case let .Next(next):
            dynProp.value = !next;
          
          default: break;
        }
      }
```

This is working but i think there must be some better solution.
I am totally new to swift and RAC so i appreciate any feedback. Thanks

**Comment by bencochran** [comment]
The following should recreate what you’re currently doing:
```swift
let dynProp = DynamicProperty(object: self.button, keyPath: "enabled")
dynProp <~ action.executing.producer.map({ !$0 })
```

Though my guess is that you’d want to actually map the action’s `enabled` property, which itself takes into account the action’s `enabledIf` property (if given upon the action’s initialization) as well as `!executing`:
```swift
let dynProp = DynamicProperty(object: self.button, keyPath: "enabled")
dynProp <~ action.enabled
```
(note that you can skip the `.property` since there’s an override for `<~` that takes a property on the right-hand-side)

**Comment by smiLLe** [comment]
Thank you @bencochran :) !
