### ISSUE TITLE
RAC3 README Issue

### ISSUE THREAD

**Issue by jcavar** [ReactiveCocoa/ReactiveCocoa#2460]
Hi everyone,
In section about throttling requests there is an example of search request. If I understood correctly, behavior of throttle has changed from RAC2 to RAC3. So for example, if we type two letters, two requests will be fired(one immediately and one after 0.5 seconds) which is not what we want. Did i misunderstand something?

**Comment by andersio** [comment]
#2075

**Comment by jcavar** [comment]
Thank you! Closing this one.

**Comment by andersio** [comment]
By the way, what you described is `delay`. `throttle` in Swift would still discard values. But it does not depend on when the latest value is sent, just the elapsed time. So in your case, if the user types two letters within say a 0.5 second interval, there would only be one request sent. Two requests are sent if the second letter happens in the next interval.

**Comment by jcavar** [comment]
Are you sure? Because I am trying this right now and if I type two letters next is called two times. First one immediately, and second one after throttle interval.

**Comment by andersio** [comment]
This should be the expected behaviour. It ensures the next value not to be sent until the elapsed time meets the specified value, while it only caches the latest value when the signal is waiting for the next sending opportunity to arise.

So in your case, if you type three letters within 0.5 second, the first change would be sent at time T, (unless the signal is waiting at time T, which would then behave like the 3rd change). After that, the second change would be cached by the signal. Then finally, the third change would overwrite the cached value (the second change) and wait till T+0.5.

**Comment by jcavar** [comment]
I am not sure that I understand what are you saying anymore. So in example with two letters, are you saying that two requests or one will be fired?

**Comment by andersio** [comment]
If the signal isn't waiting for the time to elapse (e.g. it is freshly started and never sent a value before), two Next events would be sent, and consequently two requests would be fired.

If it happens to have three or more letters being typed within 0.5 second, the subscriber would still observe only two Next events (the first and last event before 0.5 second elapsed) eventually, and thus two requests would be fired. This is because `throttle` discarded all the events sent in between.

**Comment by jcavar** [comment]
Yes, that is what I think as well. Still I am not sure why do you think that I described delay instead of throttle in my original question?

**Comment by andersio** [comment]
Yeah, I just realised after reviewing my words. That's not really true in your case of two letters within an interval of 0.5 second, in which both operators behave the same. I am sorry about that.

**Comment by jcavar** [comment]
Ok then :) I am not experienced with this so I was not sure. Thanks for your help!

**Comment by andersio** [comment]
May I apologise again. SourceKit crashes and type constraints obviously crashed my brain today, and I got some memory leaks...

I found I remembered `delay` wrong too when it means "delay the sending after n seconds", which does not match my claim of the previous reply.

I am very sorry for all these false claims. :( :(


Best Wishes,
Anders

**Comment by jcavar** [comment]
No worries :)
