### ISSUE TITLE
Best practice for async UI / Requests 

### ISSUE THREAD

**Issue by Vachman** [ReactiveCocoa/ReactiveCocoa#2518]
He everyone, I'm very new in RAC and IOS too so please give me some advice about how people usually solve problems like this.
     
I have two toggle buttons **Like** and **Dislike** in my post cell view.

In my **PostViewModel** i have:
```let vote: MutableProperty<PostVote>```

Where **PostVote** is Enum with 3 states:
1) .Liked  - for liked state
2) .Disliked - for disliked state
3) .None - when no vote

In my Post model i have 3 methods which return **SignalProducers** with embedded 
http requests to service API:  
1) like() 
2) dislike()
3) cancel_vote()

So when i implemented all logic straightforward, in another words send request when button pressed and only after success response change the vote state, everything works ok. 
But then i noticed that it is not good solution because when internet connection is slow, requests can take a while, and user can be confused because nothing happens after that he touched the button. 
    
So i decide to make request sending async. 
But there are few problems:
1) i should handle errors form requests
2) user should be able to change vote state even if some request is in process  
3) i should send request only for last state of vote

I have few idea of how to implement it but before start to do something, i
want to know is there any standard solutions for stuff like this. 

Thank you.

**Comment by twocentstudios** [comment]
In the past, I've solved this problem by having signals send multiple times, all through the same plumbing. 

The signal should first send the desired value of the transaction (i.e. the optimistic case), which will show the immediate state change in your UI that the user expects. 

Then, after the network request completes, the signal will send the same value as the optimistic case. Your UI can choose to ignore it since it won't change. 

However, if the request fails, you should send the previous value before the desired transaction through the signal in order to reset the button to its previous state. 

Depending on UX choices, you can also show an alert to the user, etc.

**Comment by Vachman** [comment]
Oh thank you. 
I think that it would be better for me use some database on my client side and implement 
some model last state sync logic with API.  

Of course it is not easy, but i hope it would be reusable.
