### ISSUE TITLE
Referencing self in event blocks

### ISSUE THREAD

**Issue by marlowcharite** [ReactiveCocoa/ReactiveCocoa#2522]
Hey all. I'm wondering if I should be using some type of modifier on self when referencing it within the event callbacks of a signal or signal producer. For instance:

``` swift
viewModel.trackTitle.producer
            .observeOn(UIScheduler())
            .startWithNext {
                self.songTitleLabel.text = $0
                // update the lockscreen when the track changes
                self.updateLockScreen()
        }
```
should I be using `[unowned self]` or `[weak self]` on the next event callback and if so why? I'm curious because I'm seeing a leaks but haven't been able to track them down yet. Any help would be appreciated

**Comment by juananime** [comment]
I guess if the block where the self instance is called is not owned as well with the same self if should be ok to don't use weak references.

**Comment by marlowcharite** [comment]
I'm more asking because the `self` in question owns the view model

**Comment by FranDepascuali** [comment]
If self has a reference to the viewModel, you should use [unowned self] or [weak self] because you are holding two strong references to self (viewModel's and self inside closure). There is a great explanation here: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html
