### ISSUE TITLE
Usage of Result vs ReactiveCocoa on function API

### ISSUE THREAD

**Issue by jdauphant** [ReactiveCocoa/ReactiveCocoa#2553]
Hello,

We have some interrogations on the usage of Result instead of ReactiveCocoa.

Why does ReactiveCocoa have a dependency on Result ?
For a synchronous simple method that can fail, is it better to return a Result or a SignalProducer ? (I have looked into the code and issue, I couldn't find an answer)

For examples :
```
extension Int {
    func divBy(divisor: Int) -> Result<Int,NSError> {
        guard divisor != 0 {
            return Result.Failure(NSError())
        }
        return Result.Success(self/divisor)
   }
}
```
or
```
extension Int {
    func divBy(divisor: Int) -> SignalProducer<Int,NSError> {
        guard divisor != 0 {
            return SignalProducer(error: NSError())
        }
        return SignalProducer(value: self/divisor)
   }
}
```

Thanks for your answers

**Comment by ikesyo** [comment]
> Why does ReactiveCocoa have a dependency on Result ?

Since we have some blocking operators such as `single()`, `first()`, `last()` and `wait()` on `SignalProducer`.

> For a synchronous simple method that can fail, is it better to return a Result or a SignalProducer ?

If the method is definitely synchronous one, you should use `Result` over `SignalProducer` for better semantics. But if that may be changed from synchronous to asynchronous or the reverse, you can use `SignalProducer` instead.

**Comment by jdauphant** [comment]
Ok thanks for the clarification
