### ISSUE TITLE
Suggestions for making Atomic, Bag, Disposable, Scheduler as new microframework.

### ISSUE THREAD

**Issue by inamiy** [ReactiveCocoa/ReactiveCocoa#2579]
Related to #2489, is there by any chance to take out:

- `Atomic`
- `Bag`
- `Disposable` 
- (and maybe `Scheduler`) 

as new microframework dependencies so that they can be used throughout other Swift frameworks and app?
I think these are very useful implementations for everyone.

**Comment by NachoSoto** [comment]
I think that would be great, but I'd recommend against making `ReactiveCocoa` _consume_ those. As much as I'm a strong believer and supporter of small frameworks (@jspahrsummers recently gave a talk about this), the current state of tools would make this a pain to use. `Carthage` makes this easier, but there are still so many pains to developing and maintaining frameworks that I think we'd go crazy if we had to maintain `RAC` as 4-5 separate libraries.

Also from the performance side, together with `Result`, one would have to link `5` frameworks in order to use `ReactiveCocoa` which can have a considerable impact in an application launch time.
