### ISSUE TITLE
Using map on long-living Signal

### ISSUE THREAD

**Issue by Vadim-Yelagin** [ReactiveCocoa/ReactiveCocoa#2585]
I have a `Signal` that can exist throughout the entire run time of the app and never complete. Then I have temporary views that observe that signal and dispose of the corresponding `Disposable` when they deinit. This seems to work fine, but if I use some functions like `map` or `filter` on that signal and then observe the resulting signal, I see that those transformed signals stay alive, and the only way to dispose of them is to destroy the original signal (which does not happen).

This is a simple example of this

	class ViewController: UIViewController {

		let (signal, observer) = Signal<Int, NoError>.pipe()

		deinit {
			observer.sendCompleted()
		}

		var counter = 0
		@IBAction func foo() {
			let currentCounter = counter
			let disposable = signal.map {
				value -> Int in
				print("GOT \(value) IN MAP #\(currentCounter)")
				return value
			}.observeNext {
					value in
					print("GOT \(value) IN OBSERVE #\(currentCounter)")
			}
			observer.sendNext(counter)
			disposable?.dispose()
			observer.sendNext(counter + 1000)
			counter++
		}

	}

If I call `foo` multiple times that's what I see

    GOT 0 IN MAP #0
    GOT 0 IN OBSERVE #0
    GOT 1000 IN MAP #0
    GOT 1 IN MAP #0
    GOT 1 IN MAP #1
    GOT 1 IN OBSERVE #1
    GOT 1001 IN MAP #0
    GOT 1001 IN MAP #1
    GOT 2 IN MAP #0
    GOT 2 IN MAP #1
    GOT 2 IN MAP #2
    GOT 2 IN OBSERVE #2
    GOT 1002 IN MAP #0
    GOT 1002 IN MAP #1
    GOT 1002 IN MAP #2
    GOT 3 IN MAP #0
    GOT 3 IN MAP #1
    GOT 3 IN MAP #2
    GOT 3 IN MAP #3
    GOT 3 IN OBSERVE #3
    GOT 1003 IN MAP #0
    GOT 1003 IN MAP #1
    GOT 1003 IN MAP #2
    GOT 1003 IN MAP #3

Is this a bug? Am I wrong to use `map` in this situation? Am I wrong to expose this long-living `Signal` and should use `SignalProducer` instead?

**Comment by andersio** [comment]
Transformed signals do not have an independent lifetime from its ultimate origin. They are basically a view forwarding events with potentially transformed values and/or errors. `takeUntil` seems more appropriate in this case, isn't it?

**Comment by andersio** [comment]
Disposing manually is also a way though, as what you did.

Anyway, in this case, the transformation block of mapped signal is still getting triggered because the disposable returned from `observe*` is only for detaching the observer, and has no effect on the signal. More importantly, the current scope hasn't exited either, so the transformed view on the signal is still yet to be deallocated. The new event from the original signal still propagates to the transformed view, despite having no observers to it.

**Comment by Vadim-Yelagin** [comment]
Okay, so the only right way to this is this

	@IBAction func foo() {
		let (terminatorSignal, terminatorObserver) = Signal<(), NoError>.pipe()
		let currentCounter = counter
		signal.takeUntil(terminatorSignal).map {
			value -> Int in
			print("GOT \(value) IN MAP #\(currentCounter)")
			return value
		}.observeNext {
				value in
				print("GOT \(value) IN OBSERVE #\(currentCounter)")
		}
		observer.sendNext(counter)
		terminatorObserver.sendNext()
		terminatorObserver.sendCompleted()
		observer.sendNext(counter + 1000)
		counter++
	}

and if `map` is put before `takeUntil` like this

		signal.map {
			value -> Int in
			print("GOT \(value) IN MAP #\(currentCounter)")
			return value
		}.takeUntil(terminatorSignal).observeNext {
				value in
				print("GOT \(value) IN OBSERVE #\(currentCounter)")
		}

then it will forever stick to the original signal. Right?
Isn't this kind of a serious pitfall? Is it documented somewhere with a huge exclamation mark next to it? Doesn't this mean that existence of that `disposable` is misleading and useless?

**Comment by andersio** [comment]
Yeah, that's what I read from the implementation. This actually makes sense, as the termination of a derived signal should not affect its upstream signal in any way, other than having one less observers. That's said I agree there should be a clear warning that `takeUntil` *must* take priority, no matter if the signal's lifetime is infinite or not. Moreover, the documentation should probably reflect the fact that operators on a `Signal` is in fact creating another `Signal`, since in some circumstances (like this open issue) this really matters.

As for the disposable returned from `observe*` though, it is just as simple as detaching an observer. It is innocent. :)

**Comment by vadim-fueled** [comment]
Yeah, but if the mapped signal has no observers and nothing references it (except for the original signal as its observer) and thus cannot possibly observe it in the future, then it makes no sense for it to continue existing and working, don't you think?

**Comment by Vadim-Yelagin** [comment]
Yeah, but if the mapped signal has no observers and nothing references it (except for the original signal as its observer) and thus cannot possibly observe it in the future, then it makes no sense for it to continue existing and working, don't you think? Is there no way to implement this behavior?

**Comment by andersio** [comment]
I think new lazy mapping operators may be introduced. I am progressing in the playground. :)

**Comment by Vadim-Yelagin** [comment]
You mean, the one that observes the original signal only when it has observers? That could work for `map` and `filter`, but not for `delay` or `flatten`.

**Comment by andersio** [comment]
I mean something like:
```
public func lazyMap<U>(transform: Value -> U) -> SignalView<U, Error, Value, Error>
```
where `SignalView` conforms to `SignalType`. This would make observation to the `SignalView` still depends on the original signal, unless it is being realised via `SignalView.signal`.

**Comment by Vadim-Yelagin** [comment]
No offense, but it's terrible for a FRP implementation to require such contraptions. RAC is too "complex made hard" already.

**Comment by NachoSoto** [comment]
There should be no need for such "lazyMap" operator.

I would also expect the `mappedSignal` to be deallocated after each `foo` invocation, so unless I'm missing something I'd say that this is a bug (@neilpa could you confirm?)

Do you think you could write a minimal version of this as a failing test? :)

**Comment by Vadim-Yelagin** [comment]
Maybe this can be solved by separating signal's interface for observing it from its implementation that receives events and dispatches them to existing observers. The observable part would retain the dispatching part, but not the other way around. When the observable part deinits, it can inform the dispatching part of that, so that it can terminate when there are no existing observers. What do you think?

**Comment by andersio** [comment]
That depends on how `map` is defined. Currently, it is meant to be "creating a new signal, and forwards events that have applied the given transform to the new signal". In this case, `mappedSignal` not being deallocated is expected, since `Signal` is defined to be terminated only upon a terminating event, and there would be none.

I have written a prototype and also added a few test cases.

https://github.com/andersio/ReactiveCocoa/pull/1

**Comment by andersio** [comment]
There are also some cases like:

**Comment by Vadim-Yelagin** [comment]
@NachoSoto https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2588
