### ISSUE TITLE
Why we need @weakify and @strongify in example code of Legacy?

### ISSUE THREAD

**Issue by flashlib** [ReactiveCocoa/ReactiveCocoa#2596]
On the [legacy](https://github.com/ReactiveCocoa/ReactiveCocoa/tree/master/Documentation/Legacy) page, the example code of section **Handling asynchronous or event-driven data sources** used @weakify and @strongify dance. But I think there is no retain cycle caused by block, thus those @weakify and @strongify dance code is useless and should be removed.

```
- (void)viewDidLoad {
    [super viewDidLoad];

    @weakify(self); // 1

    // ...

    [[self.logInButton rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(UIButton *sender) {
        @strongify(self); // 2

        RACSignal *loginSignal = [LoginManager.sharedManager
            logInWithUsername:self.usernameTextField.text
            password:self.passwordTextField.text];

            [loginSignal subscribeError:^(NSError *error) {
                @strongify(self); // 3
                [self presentError:error];
            } completed:^{
                @strongify(self); // 4
                self.loggedIn = YES;
            }];
    }];

    // ...
}
```

The ```[self.logInButton rac_signalForControlEvents:UIControlEventTouchUpInside]``` created a RACSignal, but self don't have a reference to it. 

Did I miss anything?

**Comment by RuiAAPeres** [comment]
I haven't looked at the objc implementation in a while, so I won't comment on that. But even if there is no retain cycle, there are two advantages (from an example POV):

1. It reminds people about being careful with retain cycles. ReactiveCocoa, due to its nature and heavy usage of blocks, can easily create retain cycles. By having that `@weakify`/`@strongify` dance, it establishes, in my opinion, a good practise. 
2. It show cases how ReactiveCocoa deals with this via [libextobjc].(https://github.com/jspahrsummers/libextobjc).

**Comment by mdiep** [comment]
Here's the cycle:

1. `self` retains `logInButton`
2. `rac_signalForControlEvents:` only completes/deallocs when `logInButton` is released
3. The observer would retain `self`.

If the block has a strong reference to `self`, then the button will never be released and the signal will never complete.

(3) and (4) may not need/want to use `@strongify` because the signal is short-lived and you may want `self` to have a chance to react to the result.
