### ISSUE TITLE
Question: SignalProducer of SignalProducer (or something like that)

### ISSUE THREAD

**Issue by keepingitneil** [ReactiveCocoa/ReactiveCocoa#2605]
Been poking around and I really hope this isn't a dupe.
Say I have two models: Room, User.
```
class Room {
  let creator: MutableProperty<User>
}

class User {
  let name: MutableProperty<String>
}
```

and in my code somewhere I want to observe changes to the Room and the creator's name with proper cleanup if the room changes but the old one is strongly retained somewhere still.

I want to do something like this:
``` someRoom.producer.map { $0.name.producer }.__SOMETHING__.startWithNext { [weak self] name in /*do something */ }```

is there any way to do this cleanly or will I always have to do a nested startWithNext? In the nested case: are things being disposed recursively?

Thanks
-Neil

**Comment by NachoSoto** [comment]
Hi Neil, that's a good question.

You're pretty much there! This is what you have:
```swift
let userNameProducer: SignalProducer<SignalProducer<String, NoError>, NoError> = someRoom.producer
    .map { $0.name.producer }
```

Because you're mapping each user to a new producer, you end up with a nested `SignalProducer`. So all you need to do to get what you want is `flatten` the result:
```swift
let userNameProducer: SignalProducer<String, NoError> = someRoom.producer
    .map { $0.name.producer }
    .flatten(.Latest)
```

*(For details on the different `FlattenStrategy`s you can read more [in the docs](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/BasicOperators.md#flattening-producers)*.

Which is equivalent to this:
```swift
let userNameProducer: SignalProducer<String, NoError> = someRoom.producer
    .flatMap(.Latest) { $0.name.producer }
```

I hope that helps!

**Comment by keepingitneil** [comment]
```The flatten operator transforms a SignalProducer-of-SignalProducer``` doh! how did I miss this?! Thanks!
