### ISSUE TITLE
If i implement demoteErrors (opposite of promoteErrors), would it be approved?

### ISSUE THREAD

**Issue by chrishulbert** [ReactiveCocoa/ReactiveCocoa#2609]
I'm thinking of implementing demoteErrors (opposite of promoteErrors, eg it'll convert an NSError signal to a NoError one).

If i did so, and did a PR, would it be approved? Is this functionality compatible with the RAC philosophy?

It would be useful when bridging from the ObjC style RACSignal to the Swift ones.

I'm also thinking of adding a bunch of UIKit helpers too, eg convert button taps into a Signal<Button, NoError> so we don't have to use the objc-style ones. Same question: Is this likely to be approved?

Thanks, @jspahrsummers told me on twitter i should ask here re this.

**Comment by NachoSoto** [comment]
This is similar to #2289 and #2018. Like I explained [here](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2018#issuecomment-103228169) we wouldn't want to add this operation because it encourages a bad practice. You can use `flatMapErrors` or `mapError` to explicitly handle errors, but we don't want to have an operation that ignores them without proper handling :)

> I'm also thinking of adding a bunch of UIKit helpers too, eg convert button taps into a Signal so we don't have to use the objc-style ones. Same question: Is this likely to be approved?

Good question! we definitely want to improve interoperability with `UIKit`, but we want to get RAC stable first until we move our focus to improving and extending the public API.

I've published [a gist](https://gist.github.com/NachoSoto/25b0003c1b15d7d11a8d) with some extensions, and there's also https://github.com/neilpa/Rex.

**Comment by chrishulbert** [comment]
Looks like your Gist does everything i wanted anyway! Thanks
