### ISSUE TITLE
listen to SignalProducer but not start it ? 

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2631]
Is there a way to listen to the SignalProducer with out calling start() on it ? 
and let the start be initiated somewhere else ?

my current solution is to have another Signal<Any,NoError>.pipe() and send next to the sink of this auxiliary signal ...

Cant escape the feeling that this should be easier to do .

**Comment by NachoSoto** [comment]
No, that wouldn't make sense. What are you trying to do exactly?

**Comment by edwardIshaq** [comment]
I have a signal that creates a new Contact.
the signal i started from a UI Action when the user has filled out the contact details.
I want to listen to the signalProducer that creates the new contact, but I didn't want to initiate it.

I ended up adding another Auxiliary signal to send a Next whenever the creation has happened.

**Comment by NachoSoto** [comment]
> which is started from a UI Action [...]

That looks like the root of the issue. UI actions should be represented as hot signals, because they're not controlled by the observer, but by the emitter.

You can compose that `Signal`  with a `SignalProducer` that creates a `Contact`, of course:
```swift
someAction.flatMap(.Merge) { _ in 
    return contactCreatorSignalProducer
}
```

Every time you find yourself wondering something like this, it's because you're looking for the wrong semantics :) then of the goals of RAC's types is to guide users into a good design.

Let me know if I can help you further! if you can provide more specifics I'll be happy to help.

**Comment by Suvobi** [comment]
I agree with this not being the right use case for using a SignalProducer. But purely from an academic point-of-view, the following will listen to a SingalProducer without starting it:

```Swift
bigSignalProducer.on(next: { abc in
            print("Net Event: \(abc)")
        })
```
