### ISSUE TITLE
dynamic/mutable/any/constants propert

### ISSUE THREAD

**Issue by PhilipDing** [ReactiveCocoa/ReactiveCocoa#2652]
What's difference between them? Could you give me an example of in which scenario I should use dynamic/mutable/any/constants property?

**Comment by eimantas** [comment]
I use `ConstantProperty` in a model when I know that the value won't change. It's convenient because I can use the `producer` of that property to mix and match with other signal producers.

The `MutableProperty` is a read-write version of `ConstantProperty`. With its producer you're getting all the property value changes. You can also bind that property with `<~` operator to another mutable property.

I haven't used dynamic or any property yet so maybe someone else can chime in.

**Comment by iv-mexx** [comment]
`AnyProperty` is basically a read-only property that can be observed. If you expose a `MutableProperty`, anyone could change the `value` of that property. 
E.g. in a ViewModel, you would use a private `MutableProperty` internally and only expose it as a public `AnyProperty` to the outside. The ViewModel can change the value as necessary, but other classes can only observe the changes. 

`DynamicProperty` is used to wrap properties via KVO and KVC. This might be necessary e.g. for binding to UIKit, but it is [advised against using `DynamicProperty`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L177)
I prefer to use [Rex](https://github.com/neilpa/Rex) for UIKit bindings.
