### ISSUE TITLE
UI signals vs then

### ISSUE THREAD

**Issue by andrzejtt** [ReactiveCocoa/ReactiveCocoa#2671]
Why does below <b>then</b> construct work with custom signals but does not with UI signals (then closure is not even called there)? My goal is to wait for button tap before processing text from a text field.

    #if true
        // Why does this not work?
        
        button.rac_signalForControlEvents(.TouchUpInside).then
            {
                let strongSelf = weakSelf
                return strongSelf?.textField.rac_textSignal()
            }.subscribeNext
            { object in
                let strongSelf = weakSelf
                strongSelf?.label.text = object as! String + " - 0"
            }
    #else
        // ... but this does?
        
        customSignal().then
            {
                let strongSelf = weakSelf
                return strongSelf?.textField.rac_textSignal()
            }.subscribeNext
            { object in
                let strongSelf = weakSelf
                strongSelf?.label.text = object as! String + " - 1"
            }
    #endif

**Comment by iv-mexx** [comment]
From the docs for `then`: 

> Ignores all `next`s from the receiver, waits for the receiver to complete,
> then subscribes to a new signal.

`button.rac_signalForControlEvents` does not complete (at least not on a button tap), thats why nothing happens. I guess you `customSignal()` creates a signal that completes immediately or after some time, thats why this works.

Is it correct that you want to set the text of `self.label` to the value of `self.textField` on each button tap?

I'm not really an expert, but I would try to use `sample` for that (rough, untested): 

```
self.textField.rac_textSignal().sample(self.button.rac_signalForControlEvents(.TouchUpInside))
```

**Comment by andrzejtt** [comment]
Thanks! That clears up the matter.

As for "Is it correct that you want to set the text of self.label to the value of self.textField on each button tap?" - no, I wanted to change label text to text in text field only if button was tapped before. Do you know of any RCA setup that specifies that?

**Comment by iv-mexx** [comment]
Ah ok, and once the button you want to keep updating the text label indefinitely, even if the button is tapped again?

My first idea was to use [`skipUntil`](http://rxmarbles.com/#skipUntil), but it seems this operator is not implemented in terms of another signal in RAC. Theres only `- (instancetype)skipUntilBlock:(BOOL (^)(id x))predicate;` in `RACStream` or `public func skipWhile(predicate: Value -> Bool) -> Signal<Value, Error>` in `Signal`. 

I would try to use those, but you'll need to implement the predicate block yourself instead of just doing `skipUntil(button.rac_signal.....)`

Maybe theres a better way that I don't know of though.

**Comment by iv-mexx** [comment]
Oh, seems like I was wrong (I was looking at my outdated local repo instead of the current one). Turns out, there is [public func skipUntil(trigger: Signal<(), NoError>) -> Signal<Value, Error>](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L645) implemented in `Signal`. 

However, it seems like you are currently using `RACSignal` from the old ObjC API, you would need to convert those to `Signal` to use the operators from the Swift API. 

You could also take a look at [Rex](https://github.com/neilpa/Rex) for UIKit Bindings for the Swift API

**Comment by andrzejtt** [comment]
Thanks again. I'll look into it.
