### ISSUE TITLE
injecting multiple side effects on the same event type

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2690]
I have a question.

Assuming i have a signalProducer to make a network call.
I'm trying to attach multiple side effects to the Next event.

func signInSignal() -> SignalProducer<User, NetworkError> {
    let apiCall = SignalProducer<User, NetworkError>
    apiCall.on{ next: { user in saveUser(user) }}

   return apiCall
}

//... call site: 
signInSignal().on{ next: { user in doSomethingElseWith(user) }}

I'm only getting the second side effect to perform.

Is there a way to be able to attach two side effects to the same signalProducer ?

Thanks,
Eddie

**Comment by NachoSoto** [comment]
That's because **operators don't actually modify the underlying signal**. In other words, `SignalProducer.on` returns **a new `SignalProducer`, but you're ignoring the result.

To aid with this, we added [`@warn_unused_result`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L809). I'm curious: did you not get this warning?

However, I'd recommend that you try to model your data flow by explicitly including side effects without using adhoc calls to `on`. In your example, `saveUser` could return a `SignalProducer`, as well as `doSomethingWithUser`. Then you can model your entire stream with `SignalProducer`s:
```swift
let producer = apiCall
    .flatMap(.Latest) { user in 
        return SignalProducer(values: [
              saveUser(user),
              doSomethingElseWithUser(user)
        ])
            .flatten(.Merge) // or `.Concat` if you want these to be sequential.
    }
```

Then, **only at the very end** you can call `start`, handle lifetime, etc, observe results, etc. By (over)using `on` you're hiding side effects all over the place and making it hard to handle lifetime because those operations (`saveUser`, etc) don't have a way to dispose if the outer `SignalProducer` were to be cancelled.

Hopefully that makes sense!

**Comment by edwardIshaq** [comment]
I do call start at the call site. so that the signal actually gets the work done.

But I will re model it based on you're example. Which seems to be capturing the flow i'm thinking of.

followup question:
from looking at the source code seems like each signal only gets One instance of the Next: Value->() side-effect functions, is that the case ?

**Comment by NachoSoto** [comment]
> from looking at the source code seems like each signal only gets One instance of the Next: Value->() side-effect functions, is that the case ?

Sorry, I don't think I understand what you mean. Can you elaborate?

**Comment by edwardIshaq** [comment]
Say I have a signal and I give it a side effect onComplete and return it.
then later some other code adds another onComplete side effect.
It seems like the last onComplete side effect is the one that is going to be executed and the previous ones are just dismissed.

fun getSignal() ->  SignalProducer<String, NoError> {
let mySignal: SignalProducer<String, NoError> = ...
mySignal.on(completed: completedSideEffect1)

**Comment by RuiAAPeres** [comment]
> from looking at the source code seems like each signal only gets One instance of the Next: Value->() side-effect functions, is that the case ?

It's not true. You can inject as many side effects as you want. A quick visit to the test suit will tell you that:

<img width="1441" alt="screen shot 2016-04-15 at 16 18 54" src="https://cloud.githubusercontent.com/assets/949286/14566027/b1dc77ee-0325-11e6-85f4-e18c1b670fda.png">

Assuming it would only "trigger" a single `on`, the test should have passed.

So when you inject side effects, the entire stream, [takes into consideration the previous one](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L831#L843).

**Comment by ikesyo** [comment]
@edwardIshaq Please re-read  the @NachoSoto's answer:

> That's because **operators don't actually modify the underlying signal**. In other words, `SignalProducer.on` returns **a new `SignalProducer`**, but you're ignoring the result.
>
> To aid with this, we added [`@warn_unused_result`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L809). I'm curious: did you not get this warning?
