### ISSUE TITLE
Nested SignalProducers - am I doing this right?

### ISSUE THREAD

**Issue by vojto** [ReactiveCocoa/ReactiveCocoa#2691]
Hi guys,

I'm trying to add a method on `NSUserDefaults` that would take producer of preference keys, and return the current values. So I want to pass it a changing key (signal producer) and get back the result.

This is what I cooked up:

```swift
static func rac_intProducerForKeySignal(key: SignalProducer<String?, NoError>) -> SignalProducer<Int?, NoError> {
    let producer: SignalProducer<SignalProducer<Int?, NoError>, NoError> = key.producer.map { key in
        if let key = key {
            return NSUserDefaults.rac_intProducerForKey(key)
        } else {
            return ConstantProperty<Int?>(nil).producer
        }
    }

    return producer.flatten(FlattenStrategy.Latest)
}
```

I was wondering if you guys could take a look over it and tell me if/what am I doing wrong. Should I be using different strategy? I just want to be informed whenever defaults value changes, or the key that I'm querying about changes.

Thanks!

Also this: `return ConstantProperty<Int?>(nil).producer` Something feels off about it, but I don't know how else to do it.

**Comment by NachoSoto** [comment]
Given what you're trying to do, this makes sense to me.

The only suggestion I have is to improve your "empty" result. Instead of using `ConstantProperty` you can use `SignalProducer(value:)` or better yet, `SignalProducer.empty`:
```swift
static func rac_intProducerForKeySignal(keyProducer: SignalProducer<String?, NoError>) -> SignalProducer<Int?, NoError> {
    return keyProducer.flatMap(.Latest) { key in
        return key.map(NSUserDefaults.rac_intProducerForKey) ?? .empty
    }
}
```

Here I'm using `Optional.map` to only get the producer if there is a key. That returns another optional, so using `??` we provide a fallback: `SignalProducer.empty`, which won't emit any values, but since you're using `FlattenStrategy.Latest` you'd dispose the `SignalProducer` for the previous key.

**Comment by RuiAAPeres** [comment]
@vojto if @NachoSoto's answer helped you, please close this issue.
