### ISSUE TITLE
Transforming a value into an Error

### ISSUE THREAD

**Issue by dehesa** [ReactiveCocoa/ReactiveCocoa#2700]
Hi,

I'm struggling to find out a way to **check the value provided by a `.Next` event in a SignalProducer and if it is not what I expect transform it into  a `.Failed` event**. How can I do this?

Better shown with an example.

```swift
session.rac_dataWithRequest(request: request).flatMap { (data, response) in 
     if myCheck {
          return SignalProducer(value: doSomeTransform(on: data))
     } else {
          return SignalProducer(error: someError)
     }
}.start()
```

In Functional Programming, I'd use a `flatMap` function. However, in RAC4 you need a `FlattenStrategy` (which is confusing). Also the SignalProducer returned at the end doesn't seem to end, since the `.Completed` event is never called. To test this, I add a simple `on` call before and after the `flatMap` to check when the events arrive.

Am I missing something?

**Comment by NachoSoto** [comment]
> In Functional Programming, I'd use a `flatMap` function. However, in `RAC4` you need a `FlattenStrategy` (which is confusing).

You are correct. You need to work at a higher level, not just _values_, so by `map`ping to another `SignalProducer` followed by `flatten`ing the result (or using `flatMap` directly), you accomplish what you want.
You've always been implicitly choosing a `FlattenStrategy` (in RAC 2, Rx, anywhere), you just didn't know :) This is now **explicit** in `RAC 4`, and clearly defined in this enumeration. I'd recommend starting by reading [the docs about `.FlattenStrategy`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/BasicOperators.md#flatte
ning-producers).

In your particular example, as long as the request `SignalProducer` only emits one value, none of the `FlattenStrategy`s would make a difference, **although in this case I'd strongly recommend `.Latest` because it's semantically the most correct**.

> Also the SignalProducer returned at the end doesn't seem to end, since the .Completed event is never called. To test this, I add a simple on call before and after the flatMap to check when the events arrive.

Hmm, can you share the full code? Can you also do `startWithCompleted` and see if that's invoked?

**Comment by dehesa** [comment]
Hi Nacho,

Thanks for your swift reply :) I spent a bit more time tonight working in an isolated test and I managed to bake something related to what you were talking. Thank you! Funnily, in the test the SignalProducer gets properly terminated. I might have introduce some errors in the code I am writing at work. Sorry for making you lose your time.

If you are interested, this is the test I wrote:

```swift
func test() {
     let expectation = self.expectationWithDescription("Some description")

     let request = NSURLRequest(URL: NSURL(string: "https://api.relayr.io/server-status")!)
     NSURLSession.sharedSession().rac_dataWithRequest(request).on(
          started: {     print("1. started") },
          failed: { _ in print("1. failed") },
          completed: {   print("1. completed") },
          interrupted: { print("1. interrupted") },
          terminated: {  print("1. terminated") },
          disposed: {    print("1. disposed")},
          next: { _ in   print("1. next")}
     ).flatMap(.Latest) { (data, response) -> SignalProducer<(), NSError> in
          guard let statusCode = (response as? NSHTTPURLResponse)?.statusCode where statusCode == 200 else {
               return SignalProducer(error: NSError(domain: "manolo", code: 333, userInfo: nil))
          }
          return SignalProducer(value: ())
     }.on(
          started: {     print("2. started") },
          failed: { _ in print("2. failed") },
          completed: {   print("2. completed") },
          interrupted: { print("2. interrupted") },
          terminated: {  print("2. terminated") },
          disposed: {    print("2. disposed")},
          next: { _ in   print("2. next")}
     ).start()

     self.waitForExpectationsWithTimeout(10, handler: nil)
}
```

**Comment by NachoSoto** [comment]
That makes sense! Let me know if you're still having trouble with your other example at work and I'll try to help!
