### ISSUE TITLE
Property Signal usage to update UI

### ISSUE THREAD

**Issue by Arcanfel** [ReactiveCocoa/ReactiveCocoa#2745]
Hey everyone, a noobie here!

I've been trying to wrap my head around ReactiveCocoa lately. I get the basic idea (I think), but I have run into this question lately.
My current project has a lot of read-only data displayed in the app. The data is pulled from the network and parsed into the User model that has a bunch of properties like:
```
let nameProperty		= MutableProperty<String>("")
let ageProperty		= MutableProperty<String>("")
let schoolProperty		= MutableProperty<String>("")
let occupationProperty	= MutableProperty<String>("")
```

I update these properties by setting the .value property. One of my view models have these properties.

```
self.name		= AnyProperty(self.user.nameProperty)
self.age            = AnyProperty(self.user.ageProperty)
self.school	= AnyProperty(self.user.schoolProperty)
self.occupation = AnyProperty(self.user.occupationProperty)
```
And in the view controller I observe changes in the following manner:
```
self.labelAge.text = self.viewModel.age.value
self.viewModel.age.signal.observeNext {
	age in
	self.labelAge.text = age
}
```
How do I make sure that the label text is constantly in sync with the property? Currently, I do get next updates whenever my model gets updated, however I am also interested in the current value of the model property. I know signals are not intended to contain "current" value, but maybe there is a way to sign up as an observer and get a value right away? Basically, I just want to drop the `self.labelAge.text = self.viewModel.age.value`.

**Comment by iv-mexx** [comment]
First option is to keep doing the same thing, but use the [`producer`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L13) of the Property instead of `signal` which will send the current value once upon subscription. 

In the next step, you can either use [`DynamicProperty`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L175) to wrap your UI Elements or [Rex](https://github.com/neilpa/Rex) to directly bind the properties of your viewModel to the UI.

```
self.labelAge.rex_text <~ self.viewModel.arge
```

**Comment by Arcanfel** [comment]
Thank you @iv-mexx ! I'll give your examples a try.
Also already ran into that memory leak, was pretty annoyed
