### ISSUE TITLE
combineLatest behaviour differs between Signals and SignalProducers

### ISSUE THREAD

**Issue by rustproofFish** [ReactiveCocoa/ReactiveCocoa#2753]
I'm running through basic operators at the moment and ran into a difference in the behaviour of the combineLatest operator. I'm not sure if this is a bug or my failure to understand the variation between Signals and SignalProducers.

```
let (numbersSig, numbersOb) = Signal<Int, NoError>.pipe()
let (lettersSig, lettersOb) = Signal<String, NoError>.pipe()
let signal = combineLatest(numbersSig, lettersSig)
signal.observeNext({value in print(value)})

numbersOb.sendNext(1)
lettersOb.sendNext("A")
lettersOb.sendNext("B")
```

Produces:
(1, "A")
(1, "B")

But, if I write what I would consider to be equivalent code using SignalProducers:

```
let numberProducer = SignalProducer<Int, NoError> { (observer, disposable) in
    for v in [1] { observer.sendNext(v) }
}

let letterProducer = SignalProducer<String, NoError> { (observer, disposable) in
    for v in ["A", "B", "C", "D"] { observer.sendNext(v) }
}

let combinedProducer = combineLatest(numberProducer, letterProducer)
combinedProducer.on(next: {value in print(value) }).start()

```
Output:
(1, "D")

I've deliberately left the `observer.sendCompleted() ` out of the SignalProducers as I thought that this would be responsible but that isn't the case. What am I missing?

**Comment by bromas** [comment]
Calling start on the combinedProducer handles calling start on the internal letter and number producers (Specifically see liftRight in SignalProducer.swift, where when otherProducer.startWithSignal's closure returns if will run your sendNext code). Because they are synchronous the letter producer is simply 'nexting' all of it's values before the number producer starts returning values. You can test this by reversing them in the combineLatest method call in the producer example. If you want to get the 'push values' behavior of your first test try 

`let (numbersSig, numbersSink) = Signal<Int, NSError>.pipe()
        let (lettersSig, lettersSink) = Signal<String, NSError>.pipe()
        
        let numberProducer = SignalProducer(signal: numbersSig)
        let letterProducer = SignalProducer(signal: lettersSig)
        
        let combinedProducer = combineLatest(numberProducer, letterProducer)
        combinedProducer.on(next: {value in print(value) }).start()
        
        lettersSink.sendNext("A")
        numbersSink.sendNext(1)
        lettersSink.sendNext("B")
        numbersSink.sendNext(2)
        lettersSink.sendNext("C")`

**Comment by rustproofFish** [comment]
Thanks for the explanation @bromas. I figured there would be something of this nature going on (and had totally forget about 'push' v 'pull' behaviours) - getting the specifics is very helpful.
