### ISSUE TITLE
How to improve the request code?

### ISSUE THREAD

**Issue by huanghe810229530** [ReactiveCocoa/ReactiveCocoa#2762]
MBProgressHUD.showHUDAddedTo(view, animated: true)
        let signal = Request.rac_alamofiredataWithRequest(Router.ActivetyDetail(nil)).takeUntil(requestBtn.btnCancleSignal).takeUntil(willDeallocSignal)
        signal.startWithNext() {[weak self] data, res in
            // upadateUI
            MBProgressHUD.hideHUDForView(self?.view, animated: true)
        }
        signal.startWithFailed {[weak self] error in
            // handleError
            MBProgressHUD.hideHUDForView(self?.view, animated: true)
        }

The above code snippet is bloated, especially write everywhere!I feel my code is very poor, I should be how to package?Can help me with it?

**Comment by RuiAAPeres** [comment]
@huanghe810229530 you are right in the bit where you [should prefer to bind](https://gist.github.com/RuiAAPeres/8e6ce5b17d2a59ef848713ca31f26738), [instead of injecting side effects](https://gist.github.com/RuiAAPeres/75e7981bb9a88ca4c280aa47768bbe78). The problematic part, is that `MBProgressHUD`, doesn't really provide a way to do the binding. You can either:

a) Create your own. 
2) Use what you have.

**Comment by huanghe810229530** [comment]
Very Thanks! Your answer help me!
