### ISSUE TITLE
ReactiveCocoa's Signal's generator closure

### ISSUE THREAD

**Issue by nmarisi** [ReactiveCocoa/ReactiveCocoa#2793]
When creating a new Signal, a generator closure is passed, which contains an observer. Events sent to this observer are then passed to any other observers that are attached (observing) the signal. Here's an example:

    func createSignal() -> Signal<String, NoError> {
        var count = 0
        return Signal {
            observer in
            NSTimer.schedule(repeatInterval: 1.0) { timer in
                observer.sendNext( "tick #\(count++)")
            }
            return nil
        }
    }

Observing the signal:

    let observer = Observer<String, NoError>(failed: nil, completed: nil, interrupted: nil, next: {
            value in
                print("received event: \(value)")
            
        })
     signal.observe(observer)

The output for this is naturally:

    received event: tick #0
    received event: tick #1
    received event: tick #2

If I add another observer, I get the same event, for example:

    let signal = self.createSignal()
        signal.observeNext { value in
            print("Observer 2: \(value)")
        }

The output is now:

    received event: tick #0
    Observer 2: tick #0
    received event: tick #1
    Observer 2: tick #1

This is all as expected, however, the strange thing is that if I were to send an event to the observer I initially created, it will only be seen by that observer.

For example: 

    observer.sendNext("event sent two observer")

Produces:

    received event: event sent two observer

It seems to me therefore that the observer created as part of the signal's generator closure is a special type of observer that sends events to all subsequent observers that are attached. However, sending events to any other observer only sends those events to that observer, instead of to the signal.

Why is an observer used as part of the process of instantiating a signal? Wouldn't some sort of name, say a 'producer' been preferable? In a way, an Observer can both be a consumer and a producer of events for a signal.

**Comment by RuiAAPeres** [comment]
> It seems to me therefore that the observer created as part of the signal's generator closure is a special type of observer that sends events to all subsequent observers that are attached.

Yes, from looking at the code, the `observer` passed to you:

```swift
Signal { observer in 

}
```

[Takes into consideration all the other observers](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L62#L64).

> However, sending events to any other observer only sends those events to that observer, instead of to the signal.

That's true as well. In fact doing `signal.observe(anObserver)`,  [inserts](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L134) your `anObserver` into an `Atomic<Bag>`. Moreover, `observeNext`, is just sugar for what you did here:

```swift
let observer = Observer<String, NoError>(failed: nil, completed: nil, interrupted: nil, next: {
        value in
            print("received event: \(value)")

    })
 signal.observe(observer)
```

And that's why you are able to receive these (in your example):

```
received event: tick #0
Observer 2: tick #0
received event: tick #1
Observer 2: tick #1
```

> Why is an observer used as part of the process of instantiating a signal? Wouldn't some sort of name, say a 'producer' been preferable? In a way, an Observer can both be a consumer and a producer of events for a signal.

I can't answer on the why behind the nomenclature. My two cents regarding being *both a consumer and a producer*:

It's able to [execute something]((https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Observer.swift#L39#L56)) when a given event is received ([that something is passed when initializing via closures](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Observer.swift#L20)). So it acts as a mechanism for both executing the actions and receiving the events, which is exactly what a `Signal` needs: act upon a given event. But it has no idea about composition, disposables, or what does it mean to be observed by multiple entities, like a `Signal` does.

**Comment by nmarisi** [comment]
Thanks for taking the time to answer my questions Rui, it certainly made things clearer for me. 
While it makes sense to use an observer for sending events to the signal, I still find the nomenclature there a little confusing.
