### ISSUE TITLE
Global device rotation question

### ISSUE THREAD

**Issue by nickvelloff** [ReactiveCocoa/ReactiveCocoa#2794]
Fairly new to `ReactiveCocoa`, curious if this is a suitable approach to the objective:
I would like to _cleanly_ react to device orientation changes in `UIViewController`s. The typical reaction is the removal and addition of new constraints, for instance.

The approach is to simply extend `UIViewController`, then use `ViewController` thought the app. I explored attempting to accomplish this with `protocol` and `extension` implementations, but did not land at an approach I find reasonable.
``` Swift
import ReactiveCocoa
import Result
public class ViewController: UIViewController {
    
    private var rotationNotificationDisposable: Disposable?
    private let (rotationSignal, rotationObserver) = Signal<NSNotification, NoError>.pipe()
    
    let rotationNotificationProducer = NSNotificationCenter.defaultCenter()
        .rac_notifications(UIDeviceOrientationDidChangeNotification)
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        rotationNotificationDisposable = rotationNotificationProducer
            .startWithNext { [weak self] notification in
                self?.rotationObserver.sendNext(notification)
        }
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    deinit {
        rotationNotificationDisposable?.dispose()
    }
}
```

**Comment by RuiAAPeres** [comment]
Normally you would [prefer managing lifetime with operators over explicit disposal](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/DesignGuidelines.md#prefer-managing-lifetime-with-operators-over-explicit-disposal). In your case your, "explicit disposal", is being done with `rotationNotificationDisposable?.dispose()`. So let's look at how we can improve that bit:


```swift
let rotationNotificationProducer = NSNotificationCenter.defaultCenter()
     .rac_notifications(UIDeviceOrientationDidChangeNotification)
      .takeUntil(self.willDeallocSignal())

rotationNotificationProducer
     .startWithNext { [weak self] notification in
          self?.rotationObserver.sendNext(notification)
     }
```

The `takeUntil` is part of ReactiveCocoa, but the `willDeallocSignal` not so much (although it's built on top of existing ones ✨). You can find it [here](https://gist.github.com/NachoSoto/25b0003c1b15d7d11a8d) (among others). (thanks @NachoSoto for sharing!)

In your particular case, because the clean up relies on `self.willDeallocSignal()`, more specifically `self`, you would have to either:

1. Define `rotationNotificationProducer` as `SignalProducer<NSNotification, NoError>!` (notice the implicit unwrapped optional). In this particular case, I find it ok to be like that. You can read a bit more about the why [here](http://stackoverflow.com/a/24583157/491239), specifically "A Constant That Cannot Be Defined During Initialization".
2. Explicitly dispose the  `SignalProducer<NSNotification, NoError>`, which is what you are doing.

> The approach is to simply extend UIViewController, then use ViewController thought the app. I explored attempting to accomplish this with protocol and extension implementations, but did not land at an approach I find reasonable.

For this problem, I can see three solutions from the top of my head:

1. Stick to your approach and use a `ViewController` that every `UIViewController` would inherit from. I find this one the worst:
 1. You need to remember to inherit from it, when you create a new `UIViewController`. Sometimes this is not feasible and you need to inherit from another one. You then start having multiple levels of inheritance: `ViewController <- X <- Y <- YourNewlyCreatedViewController` . A quick search about "Why inheritance is bad", will give you a good picture about the subject.
2. If the goal is to have a single point where you want to observe these events, it would be preferable (IMHO) to make it globally, instead of making each `UIViewController` subclass your `ViewController` (less of the two evils I guess). So you would have an object, that could listen for the rotations (since it's a global notification), and your `UIViewControllers` would observe this `Signal`.
3. You can follow [this](https://github.com/RxSwiftCommunity/NSObject-Rx/blob/master/NSObject%2BRx.swift) approach, from @ashfurrow and make that `Signal` part of your `UIViewController` class. Done correctly, could be the best option of all three. 

If you prefer to go with your approach `1.` (subclassing), I think it would look a bit better like this:

````swift
extension SignalProducerType {
    public func toSignal() -> Signal<Self.Value, Self.Error> {
        return Signal { observer in
            return self.start(observer)
        }
    }
}
```

````swift
import ReactiveCocoa
import Result
public class ViewController: UIViewController {

    private var signal = Signal<NSNotification, NoError>!

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {

        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

        signal = NSNotificationCenter.defaultCenter()
        .rac_notifications(UIDeviceOrientationDidChangeNotification)
        .takeUntil(self.willDeallocSignal())
        .toSignal()        
    }

    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by nickvelloff** [comment]
@RuiAAPeres Thank you! 🙇 
This is extremely helpful. I very much prefer not to subclass, so it will be one of the other options I try for sure. 
I'll try one out and post my approach (and any relevant code to share).
Thanks again. I really wanted to get this right and my approach really bugged me (as I ditch inheritance as much as possible).

**Comment by RuiAAPeres** [comment]
@nickvelloff no worries. :+1: If everything is ok from your side, please close the issue.

**Comment by nickvelloff** [comment]
Everything is great. Thanks!
