### ISSUE TITLE
Signal/Producer of a property

### ISSUE THREAD

**Issue by jozsef-vesza** [ReactiveCocoa/ReactiveCocoa#2822]
My view model exposes the following observable property,
```swift
public let comics: AnyProperty<[ComicType]>
```
which I set up during initialization
```swift
comics = AnyProperty(initialValue: [], producer: combinedProducer)
```

If I understand correctly, this will bind the value of `comics` to `combinedProducer`, which in turn, will also start the producer (so it starts sending values).

In my view controller, I observe this property
```swift
viewModel.comics.signal
    .observeOn(UIScheduler())
    .observe() { [unowned self] event in
        self.collectionView.reloadData()
}
```

Here. I observe the *signal*, instead of the producer: in theory, I could miss events, but things work just as expected. I have a feeling, that this is only due to good timing, and in practice, my controller _could_  miss some events.

So my question is: is this safe, or should I observe the producer instead?

Also, is it better to ask these questions on Slack? This way, things are "documented", but I do feel bad about flooding your issues with my questions. 😅

Thanks!

**Comment by RuiAAPeres** [comment]
> If I understand correctly, this will bind the value of comics to combinedProducer, which in turn, will also start the producer (so it starts sending values).

You are correct, you can see the bind done [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L50) and the work starting [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L217#L224). 

You are right, you might miss some events. I would also go with `observeNext` instead, because you are observing every single event (next, completed) and making a reload for each. Anyway, I think `startWithNext` is a good option.

**Comment by jozsef-vesza** [comment]
Thanks for the validation, and the suggestion as well, @RuiAAPeres !
