### ISSUE TITLE
Clarify documentation: do throttle / timeout on a queue bounce the execution of the signal on the queue?

### ISSUE THREAD

**Issue by maelp** [ReactiveCocoa/ReactiveCocoa#2837]
It is not clear from the documentation whether the behaviour of

```
signal.startOn(originalQueueScheduler)
     .throttle(0.4, onQueueScheduler: QueueScheduler.mainQueueScheduler) // or .timeoutWithError
     .map { $0.longProcessingOperation() }
```

is to run the `.map` on `originalQueueScheduler` or on `mainQueueScheduler`? And are errors / interruptions sent on the `mainQueueScheduler`? If so, I guess I should be careful if I `.materialize` errors and process the result

**Comment by RuiAAPeres** [comment]
Hi @maelp !

From the `throttle` description:

> /// Throttle values sent by the receiver, so that at least `interval`
   /// seconds pass between each, then forwards them on the given scheduler.

We also have an example in the README.md:

```swift
let searchStrings = textField.rac_textSignal()
    .toSignalProducer()
    .map { text in text as! String }
    .throttle(0.5, onScheduler: QueueScheduler.mainQueueScheduler)
```

Which helps inferring in which scheduler the the events will be forward to. Of course, this is no excuse from my side regarding the lack of better documentation. 😞

Regarding your questions:

>  to run the .map on originalQueueScheduler or on mainQueueScheduler?

The `mainQueueScheduler`.

> And are errors / interruptions sent on the mainQueueScheduler?

The `mainQueueScheduler` as well.

 >  If so, I guess I should be careful if I .materialize errors and process the result

Not really, no. `materialize` will lift the event into the monad. What this really means, in practical terms, is that i

* Instead of sending a `T`, you will receive a `.Next<T>`
* Instead of sending a `E`, you will receive a `.Failed <E>`

So instead of having a `SignalProducer<T, E>`, you will have a `SignalProducer<Event<T, E>, NoError>`. If you look at [its implementation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/790e655c5178d662ee6224208b70e8676caa1c6e/ReactiveCocoa/Swift/Signal.swift#L464#L481), nothing touches a scheduler. 

And a screenshot with a small test:

![screen shot 2016-04-29 at 11 03 53](https://cloud.githubusercontent.com/assets/949286/14913412/c8f86ffc-0dfa-11e6-8825-90bbae695fcf.png)

**Comment by maelp** [comment]
Thanks for the detailed answer, indeed the documentation of `throttle` is clear, I happened to read the one on `timeoutWithError` which states

```
/// Forwards events from `self` until `interval`. Then if signal isn't completed yet,
/// fails with `error` on `scheduler`.
```

which made me doubt whether all events were forwarded on the scheduler, or only the one for failures. From what I get:

 - `throttle` always sends events on the scheduler (which makes sense since it accumulates them there)
 - `timeoutOnError` do not change the original scheduler where `.Next` events are sent, but sends the `.Failed` event on the `scheduler` specified as a parameter

**Comment by RuiAAPeres** [comment]
> throttle always sends events on the scheduler specified as a parameter (which makes sense since it accumulates them there)

Correct.

> timeoutOnError does not change the original scheduler where .Next events are sent, but sends the .Failed event on the scheduler specified as a parameter

Correct. Still, any `.Failed` that is sent will respect the scheduler it was sent from. 

> in the case of timeoutOnError, I can often assume that .Next events are sent on the original scheduler

You shouldn't often assume, you can **expect** that behaviour.  

>  but if I .materialize events and an error happens, then I guess this will be processed on the scheduler specified as a parameter?

You will never have an error event with `materialize`, since the `.Failed` event is lifted and pushed down the streamt as a: `.Next(.Failed(Error))`. 

As I previously said, only the `error` you pass as the `timeoutOnError`'s parameter is ran on the `scheduler` you also pass. 

Let's see the implementation! 💥

```swift
return Signal { observer in

    let date = scheduler.currentDate.dateByAddingTimeInterval(interval)

    disposable += scheduler.scheduleAfter(date) {
        observer.sendFailed(error)
    }
    disposable += self.observe(observer)
    return disposable
}
```

As you can see, the `observer`, will never change scheduler, only the error param.
