### ISSUE TITLE
Why SignalProducer (Signal) with NSError and NoError can't be combined?

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#2870]
Hello,

Why should we write promoteError if we have just NSError and NoError as ErrorType?

```
     let noErrorProducer: SignalProducer<(), NoError> = ...
     noErrorProducer
         .flatMap(.Latest) {
            _ -> SignalProducer<Bool, NSError> in
            return SignalProducer(value: false)
         }
         .startWithNext {
            result in
            print(result)
      }
```

this will not compile as flatMap expects same ErrorType, ```noErrorProducer.promoteError(NSError.self)``` fixes issue, but why we should write it? If we have input NoError and we transform it to NSError result is always NSError. The same for flatten, combineLatest and other functions, if we pass NoError and NSError the will produce NSError ErrorType.

**Comment by RuiAAPeres** [comment]
One of the main goals with ReactiveCocoa is to aid the user creating apps/systems that are composable. More often than not, you will get into a point, where you need to "bend" the types, in order to fit your needs or/and please the type system. This is exactly what `promoteErrors` description tells you:

> /// This does not actually cause failures to be generated for the given signal,
   /// but makes it easier to combine with other signals that may fail;

> If we have input NoError and we transform it to NSError result is always NSError. The same for flatten, combineLatest and other functions, if we pass NoError and NSError the will produce NSError ErrorType.

Changing the signature from `NoError` to `NSError`, won't make it starting producing errors. If your `SignalProducer` inherently doesn't produce an error (`observer. sendFailed(error)`), it's not because you change its signature that it will.

**Comment by Igor-Palaguta** [comment]
I understand that we can't use flatMap with 2 different ErrorType, as Swift/ReactiveCocoa does not have ability to combine error types. But if one of type is NoError, there is no problem.  Why we can't create flatMap for NoError input source and with transform to any ErrorType? Currently compiler produces very unclear error. Definitely promoteError fixes it, but I don't see any sense to write it for this case

**Comment by RuiAAPeres** [comment]
> Why we can't create flatMap for NoError input source and with transform to any ErrorType?

Well, because `flatMap` doesn't allow that:

```swift
public func flatMap<U>(strategy: FlattenStrategy, transform: Value -> SignalProducer<U, Error>) -> SignalProducer<U, Error> {
```

Only the first type parameter is changed, the error type remains.

**Comment by Igor-Palaguta** [comment]
I see, purpose of flatMap is to change just value, not error
But allowing to transform from NoError to any ErrorType will make life easier

**Comment by RuiAAPeres** [comment]
Well, that's a discussion for a different issue.

**Comment by mdiep** [comment]
(See #2542.)

**Comment by Igor-Palaguta** [comment]
@mdiep Thanks!
