### ISSUE TITLE
ReactiveCocoa adapt to iPv6

### ISSUE THREAD

**Issue by FirstBloodFB** [ReactiveCocoa/ReactiveCocoa#2906]
I want to known what we should to adapt to iPv6-only for ReactiveCocoa?(iOS)

**Comment by RuiAAPeres** [comment]
Our only concern would be [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/dbee0971a0940dfa4a6f0f854622d13e8653c0ae/ReactiveCocoa/Swift/FoundationExtensions.swift), but since we are using `NSURLSession`, it should be fine. Taken from [here](https://developer.apple.com/library/tvos/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html):

> If you’re writing a client-side app using high-level networking APIs such as NSURLSession and the CFNetwork frameworks and you connect by name, you should not need to change anything for your app to work with IPv6 addresses.

**Comment by ikesyo** [comment]
I believe there should be no issue on RAC as @RuiAAPeres said. Closing. 😉
