### ISSUE TITLE
RAC + NSNotificationCenter, hot vs cold

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#3027]
Why reactive for NSNotificationCenter is SignalProducer instead of Signal?
Is it not hot action?
I told about 
```
extension NSNotificationCenter {
    /// Returns a producer of notifications posted that match the given criteria.
    /// This producer will not terminate naturally, so it must be explicitly
    /// disposed to avoid leaks.
    public func rac_notifications(name: String? = default, object: AnyObject? = default) -> ReactiveCocoa.SignalProducer<NSNotification, Result.NoError>
}
```

**Comment by andersio** [comment]
It is because `SignalProducer` can be interrupted/disposed.

**Comment by ajjnix** [comment]
@andersio hmm, so I can call dispose() from Disposable (after observe), but it don't dependency with ActionDisposable (for example) inside signal?
So why need return Disposable on create Signal?
```public init(@noescape _ generator: Observer -> Disposable?) ```

**Comment by andersio** [comment]
The generator disposable of a `Signal` is disposed of **only** after it terminates (i.e. completed, failed or interrupted). So if you model the notification stream as a hot signal, this disposable would never be disposed of, because logically notifications are incoming throughout the lifetime of an invocation of the app.

As a side note, the observer disposable (returned by `Signal.observe`) only silently detaches the observer from the signal. It does not have any effects on the signal.
