### ISSUE TITLE
Renaming `producer` and `signal` of `PropertyType`.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3045]
Let's make it describe the role rather than the type constraints.
🎉 

My suggestion is `values` for `producer` and `changes` for `signal`. Any thoughts on some other nice names?

**Comment by liscio** [comment]
I don't like `changes` because it implies…change. I can't recall if this is enforced by `Property` types, but it's definitely not the case for regular Signals (i.e. the same value can come across in subsequent `.next` events.)

It's hard to distinguish these two things without using the current nomenclature to "piggyback" on the existing concept of a hot vs cold signal. We'd have to consider something that would express `currentAndFutureValues` and `futureValues` for `producer` and `signal`, respectively. 

Unfortunately I don't have a good suggestion at the moment, so hopefully this stimulates someone with more creative energy at the moment…

**Comment by andersio** [comment]
Simply names them `values` and `futureValues`, perhaps? :p

**Comment by dmcrodrigues** [comment]
I don't like `changes` either, maybe `updates` could be a better possibility.

I still don't have a strong opinion about this, I see value in the proposal but at the same time I think `signal` and `producer` are actually more than type constraints because they represent in fact a concept, hot and cold signal, more than a type. I'm afraid that renaming them can introduce some confusion to distinguish which one is a hot signal or a cold signal until this rename enters deeply in our head.

**Comment by andersio** [comment]
I would worry if Swift is dynamically typed, but it is not. The type can be easily queried, and is shown in autocompletions. Moreover, when not used for `<~` kind of bindings, the observation/starting API are already quite distinctive.

**Comment by mdiep** [comment]
Closing because the core Swift code has been moved to https://github.com/ReactiveCocoa/ReactiveSwift/. Please re-open there if you're still interested in this.
