### ISSUE TITLE
Help with conditionally flattening 

### ISSUE THREAD

**Issue by mdarnall** [ReactiveCocoa/ReactiveCocoa#3058]
Hi,

I'd like to implement behavior where I can flatten the values from two `SignalProducer`s. But I only want to send the second signal producer if the first completes _without_ sending a value. Any tips on existing operators that can help me acheive this, or what It would look like to implement this? 

```
let innerProducer1: SignalProducer<UIImage, NoError> = readFromDiskProducer()
let innerProducer2: SignalProducer<UIImage, NoError> = fetchFromNetworkProducer()

let outerProducer = SignalProducer<SignalProducer<UIImage, NoError>>{
  // send innerProducer1 immediately

  // only send innerProducer2 if innerProducer1 completes without sending a value

}.flatten(.Merge)

```

The idea in this is to first attempt to read a resource from disk. If the value exists (and is sent) it won't execute the second SignalProducer which will attempt to fetch the resource from the network. 

Thanks!

**Comment by ikesyo** [comment]
Maybe something like this? I assume that your producers only send one value per subscription.

```swift
let outerProducer = readFromDiskProducer()
    .concat(fetchFromNetworkProducer())
    .take(1)
```

Thus, the resulting producer will complete without starting `fetchFromNetworkProducer()` if `readFromDiskProducer()` sends a value, otherwise `fetchFromNetworkProducer()` will be started and a value from the producer will be send.

**Comment by mdarnall** [comment]
Yeah, I think given my producers only send one value this will work. Thanks!
