### ISSUE TITLE
A list of PRs for property enhancements & lifetime protocols

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3061]
Well since these are pretty scattered while some being dependent, I thought it would be nice to have a list that sums them up.

#### Merged PRs
1. #3023 Unifying read-only properties.
 1. Meld `ConstantProperty` and `AnyProperty` into a single `Property` type.
 1. Introduce `PropertyType.sources` for composed properties to capture their sources.
 1. Class bound `PropertyProtocol`.<br><br>
1. #3046 Reuse Atomic in MutableProperty.
 1. Code reuse.<br><br> 
4. #3078 Fix the inconsistency of composed properties.
 1. Composed properties use a replayed producer to provide a consistent value with regard to the property's producer and signal.<br><br>

#### Current PRs
2. #3030 Lifetime
 1. A new operator `take(within:)` for both `Signal` and `SignalProducer`.
 1. Add `NSObject.lifetime`.<br><br>
3. #3054 Drop `rac_values` in `DynamicProperty`.
 1. _Require #3052 for `NSObject.lifetime`._
 1. Remove the ReactiveObjC dependency of `DynamicProperty`.
 1. Stateless `DynamicProperty`.<br><br>

#### Future PR ideas
1. Properties expose a `Lifetime`.
 1. All property types are required to expose a lifetime token. <br><br>
1. A new `BindingConsumer` protocol.
 1. Precisely model all properties that can consume values by establishing a binding. e.g. properties of UIKit classes. 
 1. Inherit by `MutablePropertyProtocol`.
 1. The target must expose a `Lifetime` token.<br><br>
1. Changes to binding operators.
 1. Move binding operators to `BindingConsumer`. ([SE-0091](https://github.com/apple/swift-evolution/blob/master/proposals/0091-improving-operators-in-protocols.md))
 1. Simplified implementation using `take(during:)` and `Lifetime` tokens. :)
 1. Align the behavior of the binding disposables with those returned by `Signal.observe` and `SignalProducer.start*`.<br><br>
1. Semantic changes of `DynamicProperty`.
 1. Supply a custom binding implementation, so that bindings act directly on the wrapped object via KVC. Consequently, the `DynamicProperty` can be freed from the retainment by its wrapped object.
 1. Adapt the capturing semantics of composed/existential properties.

**Comment by mdiep** [comment]
> Well since these are pretty scattered while some being dependent, I thought it would be nice to have a list that sums them up.

Thank you! I promise I'm trying to get to these. But I've been focusing on high priority PRs and all taking some vacation time. ☺️

**Comment by liscio** [comment]
My one major concern surrounds this part:

> * A new BindingTarget protocol.
>     1. Precisely model non-observable properties that make sense as a binding target. e.g. properties of UIKit classes.
>     2. The target must expose a Lifetime token.

Bindings in Cocoa are typically two-way relationships. When you bind a model value to a UI control, changes in the UI control set the model, and changes in the model update the UI control.

In my bindings work on Rex (https://github.com/RACCommunity/Rex/pull/84/files) I have separated out the two sides of this relationship into a `PropertyBinding` and `ConsumerBinding`. I have also created a few operators that allow you to model this data flow using `<~`. (Side note: I am not locked into this naming, and merely wanted to get the concept going for a project that I needed to ship…)

We will likely be able to merge these efforts together, however I think we need to be cautious about using the term "Binding" without some concept of direction (i.e. Producer vs Consumer, Setter vs Getter, etc.) or other disambiguation, as it will *certainly* cause confusion with the richer, longer-standing concept of bindings from Cocoa UI code.

UI bindings represent a very large topic, and Cocoa's Bindings system—though not very well-understood—have a lot of features that should not be ignored. For starters, there's value transformation (handled fairly well by `map`, but not bidirectional) and validation which are very important for the majority of use cases.

Anyway, I'm excited to see this stuff getting some attention!! Hope I can pitch in again sooner rather than later.

**Comment by andersio** [comment]
`BindingTarget` is exactly modelled after `ConsumerBinding`. My main concern here is only the one way bindings though. 

> We will likely be able to merge these efforts together, however I think we need to be cautious about using the term "Binding" without some concept of direction (i.e. Producer vs Consumer, Setter vs Getter, etc.) or other disambiguation, as it will certainly cause confusion with the richer, longer-standing concept of bindings from Cocoa UI code.

The mutability and the `<~` operator should have implied a direction, and `BindingTarget` adds another set of guarantees to the mix (`PropertyProtocol` and `MutablePropertyProtocol`) we have at this moment. But I agree that the differentiation is important.

**Comment by andersio** [comment]
Having followed swift-evolution for a few months, I think it might be valuable to share a few words on the fate of the `Property` types, with the list of "interested but not committing" list of Swift 4.0 Stage 2 features.

1. Property reflections

 The community has an interest behind Groff's idea of "lenses". For example, with lenses we may  pass around `&view.isHidden` as a closure like `() -> inout Bool`, creating a KVC-like ground for many dynamic uses.

 However, the "lenses" are expected to capture a reference to the object. This makes it less a viable replacement of the proposed `BindingConsumer` protocol, since our binding system weakly reference both ends, and observe the deinitialization additionally to tear down the binding.

2. Property behaviors

 The community had an initial proposal in property behaviors, which is now _expected_ to be part of the Swift 4.0 Stage 2 development. While our property types might be convertible into behaviors, IMO there are quite a few pieces needed with the current (halted) proposal:

  1. Out-of-band access to the underlying behavior (for exposing the producer & signal). e.g. for `var [observable] name: String`, we can access the producer by `name.[observable].producer`.
  2. Constrainable in function signature with out-of-band access too.

3. Hygiene macro

 Well, probably the last resort for our binding magic? But the scope of such system is not known yet, and there is barely discussion on this so far.

**Comment by mdiep** [comment]
These PRs are all merged. ✨
