### ISSUE TITLE
How to Cancel NSURLSessionDataTask 'Inside' A RACSignal

### ISSUE THREAD

**Issue by jac300** [ReactiveCocoa/ReactiveCocoa#3063]
I am using Reactive Cocoa to merge & collect multiple network requests together (as RACSignals) like so:
   
     [[[RACSignal merge:requestSignals] collect] subscribeNext:^(NSArray *results){...}

Each individual RACSignal is created like so:

    - (RACSignal *)signalForMyRequest { RACSignal *signal = 
          [RACSignal createSignal:^RACDisposable  
              (id<RACSubscriber> subscriber) {
                  NSURLSessionDataTask *task = [self myRequest success:nil failure:nil];
                  return [RACDisposable disposableWithBlock:^{
                  [task cancel];
            }];
        }];

        return signal;
    }

This all works fine. My question is this: is there a way to cancel the actual request (i.e. the `NSURLSessionDataTask`) inside of an individual RAC signal? I am using a `subscribeNext:` block on the merged signal, which returns a `RACDisposable` - which I can dispose, but that applies to the entire merge operation rather than an individual signal. I was looking at things like `takeUntil:` but this is described as "releasing the signal" and I'm not certain if that will in turn cancel the request it contains or not. Any help is appreciated.

**Comment by mdiep** [comment]
> I was looking at things like takeUntil: but this is described as "releasing the signal" and I'm not certain if that will in turn cancel the request it contains or not

Yes, that will dispose of the signal, which will cancel the request.

Something like `takeUntil:` or `switchToLatest` is generally the best way to do something like this. If you use `takeUntil`, you'll need to apply it before the `merge:` so that it's applied to the individual signals.

If you'd like more specific help, you'll need to provide some more detail about what you're doing. ☺️
