### ISSUE TITLE
Flatten signal of optional signals.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3176]
I wonder if anyone feels there is a need for `flatten` and `flatMap` that flattens optional producers and signals, by treating `nil` as equivalent of empty signals/producers.

e.g.
```
// let producer: SignalProducer<MyViewModel?, NoError>
producer.flatMap { $0.title.producer ?? .empty }

// `nil` is treated as `SignalProducer.empty`.
producer.flatMap { $0?.title.producer }
```

This is especially handy for `PropertyProtocol`, since unlike `Signal` and `SignalProducer`, the concrete type varies.

```
// let producer: MutableProperty<MyViewModel?, NoError>
producer.flatMap { $0.title ?? Property(value: "default") } // Invalid.
producer.flatMap { $0.title ?? MutableProperty("default") } // OK but clumsy.

// Since a property has a guarantee of always having a value, it flattens a sequence of `Property<U>?` into `Property<U?>` instead.
producer.flatMap { $0?.title } // Produces `Property<String?>`.
```

**Comment by NachoSoto** [comment]
I see 2 potential problems with this:
- Adding hidden semantics like this could lead to confusion. I'd rather make the type system force users to decide what the default should be (why `.empty` and not `.never` and not `SignalProducer(value: defaultValue)` and not `SignalProducer(error: .noValue)`?)
 - More overloads will only lead to more compiler ambiguity, especially due to `Optional` promotion.

**Comment by mdiep** [comment]
Closing because the core Swift code has been moved to https://github.com/ReactiveCocoa/ReactiveSwift/. Please re-open there if you're still interested in this.
