### ISSUE TITLE
Why was startWithNext deprecated?

### ISSUE THREAD

**Issue by gbrhaz** [ReactiveCocoa/ReactiveCocoa#3230]
`startWithNext` has now been deprecated with a message saying:

"This SignalProducer may emit errors which must be handled explicitly, or observed using startWithResult:"

How is `startWithNext` any worse than saying `start`? 

I have created a few extensions on `SignalProducerType` for `on(failed:)` scenarios. `startWithNext` was a useful method to improve readability. 

I've had a look through https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3011

I guess what I'm saying is: Signals are value types that can get constructed fluently. I am not ignoring errors, but I still want to use `startWithNext`; the framework isn't aware that I am not ignoring errors. What are the reasons behind doing this when there are so many 'side-effects' on signals?

**Comment by sharplet** [comment]
Firstly, just want to make sure—are you aware of `startWithValues`? `startWithNext` was renamed in https://github.com/ReactiveCocoa/ReactiveSwift/pull/8.

Since that rename happened, I think we should revisit the deprecation messages, because they've become misleading. You can still do what you're trying to, _provided you have a producer with error type `NoError`_.

The new `startWithResult` method is designed to help you not to forget error handling. However, having helpers to handle errors in a different part of the signal chain is a great approach—instead of using `on(failed:)`, you may just need to signify that youv'e handled the error by transforming the error type to `NoError`:

```swift
producer
  .flatMapError { error -> SignalProducer<T, NoError> in
    // handle the error
    return .empty
  }
  .startWithValues { value in
    // use the values
  }
```

Hope that helps.
