### ISSUE TITLE
I can't bind property

### ISSUE THREAD

**Issue by JQHee** [ReactiveCocoa/ReactiveCocoa#3384]
let label: UILabel = UILabel()
        testMD.name = "name"
        label.reactive.text <~ testMD.name
 Binary operator '<~' cannot be applied to operands of type 'BindingTarget<String?>' (aka 'BindingTarget<Optional<String>>') and 'String?'

**Comment by iv-mexx** [comment]
It seems like your `testMD` is a `String?`, thats why it does not work.

In your case, I guess you would want to change `testMD.name` to be a `Property<String?>`, then the binding works. 

Other things that could be on the right side (source) of a binding are `Signal` and `SignalProducer`

**Comment by JQHee** [comment]
let resultSignalProducer = self.testMD.reactive.values(forKeyPath: "name").map{$0}
        uerNameTF1.reactive.text <~ resultSignalProducer

ERROR: Ambiguous reference to member 'text'

**Comment by iv-mexx** [comment]
In the first example, `.pipe()` returns a Tuple (as seen by the Error Message) `'(Signal<String, NoError>, Observer<String, NoError>)'`, in that example you would need to do 

```
let (signal, observer) = Signal<String, NoError>.pipe()
uerNameTF1.reactive.text <~ signal
```

**However** I think you should not need to use Signal.pipe (but I can only guess what you're trying).

Based on your first example I would try to go with something like this:

```
class MD {
    let name: MutableProperty<String>('')
    ...
}

let testMD = MD()
...
uerNameTF1.reactive.text <~ testMd.name
```

If this is not what you are looking for please try to explain what you are actually trying to achieve instead of just posting snippets with error messages
