### ISSUE TITLE
Action 'execute' closure not executed

### ISSUE THREAD

**Issue by gbuela** [ReactiveCocoa/ReactiveCocoa#3387]
I should try to reproduce this in a small app that you could check out, because you guys don't need to wrap your heads around the stuff I'm writing. But first let me give it a shot at describing the issue to see if you can give me any clues.

I have an Action that is initialized with this API:

    public convenience init<P : PropertyProtocol where P.Value == Bool>(enabledIf property: P, _ execute: @escaping (Input) -> ReactiveSwift.SignalProducer<Output, Error>)

I'm wrapping the action with a CocoaAction so that a button triggers the action. I derive the button's enabled state from the action's.

I have different flows on app launch. In one, the input for the action is fetched from a service call; in the other it is read from local storage. In either case that input is set to a Property used by the action as input.

On the 1st scenario everything works well. On the 2nd one, I get the enabled button (hence action is enabled) but it does nothing -- the 'execute' closure above is not called.

Any ideas?

**Comment by sharplet** [comment]
It's hard to say why the action is not being execute the second time. It could be worth checking that the `SignalProducer` returned for the first execution is definitely terminating—the `logEvents()` operator is useful for debugging that.

Another thing I could recommend is, because you are using the state of another property as input to the action, try switching to the `Action(state:enabledIf:_:)` initialiser. You can use `Property.combineLatest(yourStateProperty, yourEnabledProperty)` to combine your two properties.

**Comment by gbuela** [comment]
Thanks. Actually it was something stupid I did with the button's appearance and nothing to do with the Action. On the 2nd scenario the button was actually disabled but looked enabled. The appearance was based on some state and not on the actual enabled state.
Thanks, and sorry :)
