### ISSUE TITLE
Binding can not use!

### ISSUE THREAD

**Issue by JulianSong** [ReactiveCocoa/ReactiveCocoa#3485]
When I use Binding like this.
`self.textLabel?.reactive.text <~ self.viewModel?.albumName`
I got an error 
` Binary operator '<~' cannot be applied to operands of type 'BindingTarget<String?>?' and 'MutableProperty<String>?'`
And I define albumName like this
`let albumName = MutableProperty<String>("")`
Did I use it correctly?

**Comment by andersio** [comment]
You are defining stuff correctly, just that the binding cannot be established because both LHS and RHS of `<~` are optional. If you are sure that the text label and the view model always exists at that point, force unwrap them.

```swift
self.textLabel!.reactive.text <~ self.viewModel!.albumName
```

Otherwise, you would need to find ways to make these properties in your VC/view non-optional.

**Comment by JulianSong** [comment]
👍 Thank you for your answer! I changed my code and now it works fine.
