### ISSUE TITLE
crash on iphone5 with xcode9 beta6

### ISSUE THREAD

**Issue by sandyway** [ReactiveCocoa/ReactiveCocoa#3507]
RAC:6.0.1
RAS: 2.0.1

If I run this in viewDidLoad:
NotificationCenter.default.reactive
            .notifications(forName: Notification.Name(rawValue: notificationName))
            .take(during: self.reactive.lifetime)

or run this in init:
playingIndex.producer
            .take(during: reactive.lifetime)
            .skipRepeats()
            .startWithValues

will crash with log:
fatal error: Unexpected pthread mutex error code: 11: file /Users/songway/development/***/Pods/ReactiveSwift/Sources/Atomic.swift, line 190

If I push code above not in viewDidLoad or init,there's no crash

**Comment by andersio** [comment]
Which version of RAS and RAC does the app use?

**Comment by sandyway** [comment]
6.0.1

**Comment by andersio** [comment]
Does this issue appear on 64-bit ARM devices? I found it odd but I do have a suspicion.

**Comment by sandyway** [comment]
don't appear on 64-bit ARM devices.

**Comment by andersio** [comment]
Since you are using CocoaPods, would you mind to try replacing `PTHREAD_MUTEX_ERRORCHECK` in this particular line in ReactiveSwift's `Atomic.swift` to `PTHREAD_MUTEX_NORMAL`?
> https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Atomic.swift#L159
> ```
> pthread_mutexattr_settype(attr, Int32(recursive ? PTHREAD_MUTEX_RECURSIVE : PTHREAD_MUTEX_ERRORCHECK))
> ```

`pthread_mutex_trylock` is not supposed to fail with `EAGAIN` based on the documentation. As this doesn't fail on 64-bit platforms, I can only suspect that the 32-bit version of pthread has a bug or undocumented behaviour.

**Comment by sandyway** [comment]
Thanks,I'll try

**Comment by sandyway** [comment]
Change PTHREAD_MUTEX_ERRORCHECK to PTHREAD_MUTEX_NORMAL resolved the problem!
Thank you!
