### ISSUE TITLE
How best to separate UIButton styling for Action isEnabled vs isExecuting?

### ISSUE THREAD

**Issue by tikitu** [ReactiveCocoa/ReactiveCocoa#3568]
Hi folks,

If I have a `UIButton` with `reactive.pressed = CocoaAction(myAction)` where `myAction` can be enabled or disabled based on some property `shouldBeEnabled`, I have the following problem: I want to give the `UIButton` different styling when `myAction` is disabled because `shouldBeEnabled` went `false`, and when `myAction` is disabled because it's executing.

(In particular: I give the button "faded" styling when the action is explicitly turned off, while I want to leave it unfaded while the action is executing.)

If I just use the standard UIKit stuff (`myButton.setBackgroundImage(disabledImage, for: .disabled)` and so on) I get the disabled styling also while the action is in progress. Is there any standard, tidy way to sidestep this?

(So far what I'm doing is *not* using `setBackgroundImage(_:for:)` but triggering explicit button-style changes off `myAction.isExecuting` and `shouldBeEnabled`. This is doable but is making it more difficult to extract a reusable utility, plus of course it's preferable to use the UIKit mechanisms wherever possible instead of having to roll our own.)

**Comment by sharplet** [comment]
Would it work in your case to combine `.disabled` with another control state flag in order to model this explicit vs. implicit disabling? For example, maybe you could repurpose `.selected` to indicate that the button is enabled, leading to the following truth table:

- selected & enabled: completely enabled
- selected & disabled: action executing
- unselected & disabled: explicitly turned off
- unselected & enabled: ???

The only issue here is that last case, where technically your control could be enabled and unselected, and thus still have user interaction enabled. You might need a custom subclass to actually implement this custom disabled state and maintain the new invariants you need (which can be a fair bit of code, unfortunately).

In any case, these are just some ideas. Another alternative would be to make a new `reactive.something` action target, modelled off `reactive.pressed`, that manages side effects on the button in a way you can control.

**Comment by tikitu** [comment]
Hm. I like the idea of copying `reactive.pressed` but that runs into the `associatedValue` problem: there's a whole extensive setup to work around the fact that extensions can't store properties, but it's `internal` so I can't use it.

Thanks for the suggestion to combine with more control flags, that might be a winner. There's also the application-specific `UIControlState` bits, which is more UIKit-robust (but again requires subclassing, unless I missed something).

**Comment by sharplet** [comment]
Yep, I've used the application-specific bits before — it works really well, it just takes a fair amount of code to get it solid.

**Comment by sharplet** [comment]
> …there's a whole extensive setup to work around the fact that extensions can't store properties, but it's `internal` so I can't use it.

@ReactiveCocoa/reactivecocoa what it be reasonable to make some of that plumbing public? Or is there a more flexible API we can expose?

**Comment by mdiep** [comment]
I think the best solution would probably be to allow some composition with `CocoaAction`s. i.e. you should be able to create your own `UIButton.reactive.myPressed` that _uses_ `.pressed` but adds some custom logic. Probably that would mean adding a new `init` to `CocoaAction`.

I don't think we want to expose associated values. We should make it easy to compose new things from our wrappers of AppKit and UIKit.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
