### ISSUE TITLE
NSButton doesn't send state values when changed programatically

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveCocoa#3644]
I'd assume it's intended behaviour… Is it?

**Comment by mdiep** [comment]
Yes, this is intentional.

It's designed so that the view isn't the source of truth. Your model/view model should act as the source of truth. Changes from the view should be directed to the view model. Then other things can observe the view model.

This is intended to clarify ownership and eliminate the problem of cycles.

**Comment by andersio** [comment]
It is also the behaviour of UIKit, where changes made programmatically would not trigger any action message, since you are supposed to know any change made by you.
